import type { Problem } from '../../types';
import { problem as make } from './helper';
const p = (...args: Parameters<typeof make> extends [string, ...infer R] ? R : never) => make('wmq3', ...args);
const r = String.raw;
const graph = (name: string) => '\n\n![独立绘制的参考图](figures/wmq3/' + name + '.svg)';
const pic = (name: string) => ({ figures: ['figures/wmq3/' + name + '.png'] });
const multi = r`$x(t)=10\cos(800\pi t+\pi/4)+7\cos(1200\pi t-\pi/3)-5\cos(1600\pi t)$，定义在全时域。`;
const conv = r`题图 3.18 的两个矩形均以0为中心：$x_i(t)=E_i$（$|t|<\tau_i/2$），带外为0；$\tau_1,\tau_2>0$，$E_1,E_2>0$。`;
const allpass = r`已知 LTI 系统的频率响应为 $H(j\omega)=(1-j\omega)/(1+j\omega)$，求零状态响应。`;
const lp = r`理想低通 $H(j\omega)=e^{-j2\omega}$（$|\omega|<2\pi$），带外为0。$\mathrm{Sa}(v)=\sin v/v$，在0处取极限1。`;

// 教材纸书第61–84页，PDF第69–92页；老师圈题3.11/13/14/20/21/26沿用hw3。
// 26道其余原题拆为51来源单元；完全同题在index.ts合并，不改旧进度编号。
export const wmq3: Problem[] = [
  p('3.1', ['3.1'], 'concept', r`$\omega_0>0$，证明 $\{\cos(n\omega_0t):n=0,1,2,\ldots\}$ 在 $(0,2\pi/\omega_0)$ 正交，并给各函数的平方积分。此项按808圈画表为了解项。`, r`记 $T=2\pi/\omega_0$，则
$$\int_0^T\cos(n\omega_0t)\cos(m\omega_0t)dt=\begin{cases}0,&n\ne m,\\T,&n=m=0,\\T/2,&n=m\ge1.\end{cases}$$`, r`不同非负整数 n、m 下，积化和差给 $(\cos[(n-m)\omega_0t]+\cos[(n+m)\omega_0t])/2$。两个频率均非零整数倍，积满一个周期后为0。同阶时另算：常数1的平方积分为T；非零阶用 $\cos^2=(1+\cos2n\omega_0t)/2$ 得T/2。不能把n=0误用T/2。`, { type: '分析', minutes: 5, note: '3.1正交函数集为一星了解项，保留原重要性。' }),
  p('3.2(1)', ['3.2'], 'fourier-series', multi + r`画双边频谱，给每条谱线的复值，并可分幅度、相位作图。明确级数系数与 FT 冲激权重。`, r`取 $\omega_0=400\pi$，非零级数系数为
$$C_{\pm2}=5e^{\pm j\pi/4},\quad C_{\pm3}=\tfrac72e^{\mp j\pi/3},\quad C_{\pm4}=-\tfrac52.$$
其他为0；$X(j\omega)=2\pi\sum_n C_n\delta(\omega-n\omega_0)$。负实系数的相位可取π。` + graph('a3-2-mag') + graph('a3-2-phase'), r`用 $A\cos(\omega t+\theta)=\frac A2e^{j\theta}e^{j\omega t}+\frac A2e^{-j\theta}e^{-j\omega t}$。幅度−5保留在两条系数中，或等价改写成幅度5、相位π。实信号满足 $C_{-n}=C_n^*$。双边级数幅度分别为5、7/2、5/2，不是单边余弦幅度10、7、5；FT的冲激权重再乘2π。`, { type: '画图', minutes: 10, verified: 'corrected', note: '纸书第62页仅画正频率，并把余弦幅度与双边复谱混在一起，负项未补相位π。按题干要求给完整双边复值，两种谱口径分开。' }),
  p('3.2(2)', ['1.2'], 'period', multi + '判断周期性并求基本周期。', '$T_0=1/200$ 秒，基本角频率 $400\pi$ rad/s。', r`三个频率为400、600、800Hz，共同基本频率是最大公约数200Hz；谐波次数2、3、4的公约数为1，且系数均非零，所以基本周期不是1/400，而是1/200。`, { minutes: 4 }),
  p('3.2(3)', ['3.2', '1.2'], 'fourier-series', multi + r`加入 $\cos(1000\pi t+\pi/2)$ 得 $y(t)$。频谱如何变化，是否周期，基本周期多少？`, r`增加角频率 $\pm1000\pi$ 两条谱线，级数复系数为 $j/2,-j/2$。$T_0=1/100$ 秒、$\Omega_0=200\pi$。新基频下 $C_{\pm4}=5e^{\pm j\pi/4},C_{\pm6}=\tfrac72e^{\mp j\pi/3},C_{\pm8}=-5/2,C_5=j/2,C_{-5}=-j/2$。`, r`新增频率500Hz，与原400、600、800Hz的最大公约数为100Hz。原物理谱线位置不变，但换到新基频后谐波下标要加倍；不能保留旧下标2、3、4同时声称新基频200π。新分量的FT冲激权重为 $j\pi,-j\pi$。`, { minutes: 7, note: '纸书第62页把新增“频率”写成1/500，实际频率是500Hz，1/500是该分量的周期；最终公共周期1/100正确。' }),
  p('3.3(1)', ['3.2'], 'fourier-series', r`求 $x(t)=e^{j200t}$ 的傅里叶级数，给基本周期和非零复系数。`, r`$T_0=\pi/100,\omega_0=200$，$C_1=1$，其余0；$x(t)=\cos200t+j\sin200t$。`, r`该复信号已是单个正频率的复指数，不能为它补一个负频率共轭项：共轭对称只适用于实时域信号。周期要求 $200T=2\pi k$，最小正值π/100。`, { minutes: 3 }),
  p('3.3(2)', ['3.2'], 'fourier-series', r`求 $\cos[\pi(t-1)/4]$ 的三角及复指数傅里叶级数。`, r`$T_0=8,\omega_0=\pi/4$；
$$x(t)=\tfrac1{\sqrt2}\cos(\pi t/4)+\tfrac1{\sqrt2}\sin(\pi t/4),\qquad C_{\pm1}=\tfrac12e^{\mp j\pi/4}.$$
其他复系数为0。`, r`先展开时移后的余弦：相位是−π/4。正频率系数为 $(1-j)/(2\sqrt2)$，负频率为共轭；不要把时间减1直接解释成频率减1。`, { minutes: 5 }),
  p('3.3(3)', ['3.2'], 'fourier-series', r`求 $\cos4t+\sin8t$ 的三角及复指数傅里叶级数。`, r`$\omega_0=4,T_0=\pi/2$；$a_1=1,b_2=1$，其他三角系数与直流为0；$C_{\pm1}=1/2,C_2=-j/2,C_{-2}=j/2$。`, r`4、8rad/s给第一次和第二次谐波。正弦用 $(e^{j8t}-e^{-j8t})/(2j)$ 展开，正频率虚部为负，负频率虚部为正。这里采用 $x=a_0+\sum_{n\ge1}(a_n\cos n\omega_0t+b_n\sin n\omega_0t)$，a₀是平均值。`, { minutes: 4 }),
  p('3.3(4)', ['3.2'], 'fourier-series', r`周期 $T=2$，一周期内 $x(t)=e^{-t}$（$-1<t<1$），周期延拓。求三角及复指数傅里叶级数。三角常数项按平均值a₀记。`, r`$\omega_0=\pi$；对任意整数n，
$$C_n=\frac{(-1)^n(e-e^{-1})}{2(1+jn\pi)}.$$
$a_0=(e-e^{-1})/2$；$n\ge1$ 时
$$a_n=\frac{(-1)^n(e-e^{-1})}{1+n^2\pi^2},\qquad b_n=\frac{(-1)^n n\pi(e-e^{-1})}{1+n^2\pi^2}.$$
级数在跳变处收敛到两侧平均值。`, r`按定义 $C_n=\frac12\int_{-1}^1e^{-(1+jn\pi)t}dt$，上下限的因子 $e^{\pm jn\pi}=(-1)^n$，得到上式。再由 $a_n=2\Re C_n,b_n=-2\Im C_n$ 取实虚部。均值是sinh1，非1/2。把原周期片段e⁻ᵗ直接当全时间指数会改变题目。`, { minutes: 10, verified: 'corrected', note: '纸书第63页a_n分子误为e+e^(−1)，应为e−e^(−1)；指数级数基频π也须保留。独立积分和复系数还原给同一结果。' }),
  p('3.3(5)', ['3.2'], 'fourier-series', r`题图 3.3 是在−1与1之间上升的锯齿，跳变点的横坐标标注却不一致。求其傅里叶级数，说明采用哪一种周期解释。`, r`若采用原解答的 $T=2$、$x(t)=t$（$-1<t<1$）周期延拓，则
$$x(t)=\frac2\pi\sum_{n=1}^{\infty}\frac{(-1)^{n-1}}n\sin(n\pi t),\quad C_0=0,\quad C_n=\frac{j(-1)^n}{n\pi}\ (n\ne0).$$
仅凭原图互相冲突的跳变坐标不能无条件确定该周期。`, r`上述条件下信号实奇，a₀和余弦系数为0，$b_n=2\int_0^1t\sin(n\pi t)dt=2(-1)^{n-1}/(n\pi)$。正频率系数必须为纯虚 $-jb_n/2$。图上相邻锯齿的跳变标1、2、3，靠原点两端又为−1、1；不能把不一致的标注当作确定数值题。`, { ...pic('q3-3-5'), minutes: 8, verified: 'uncertain', note: '纸书第62页图的重复跳变坐标与第63页T=2解释冲突；原解答复系数还漏虚数因子。保留明确T=2条件解，排除自动组卷和808能力证据。' }),
  p('3.3(6)', ['3.2'], 'fourier-series', r`周期T=4，一周期 $x(t)=\sin(\pi t)$（$0<t<2$）、其余 $2<t<4$ 为0，周期延拓。求三角及复指数傅里叶级数。`, r`$\omega_0=\pi/2,C_0=0$；
$$C_n=\begin{cases}-j/4,&n=2,\\j/4,&n=-2,\\2/[\pi(4-n^2)],&n\text{为奇数},\\0,&n\text{为其他偶数}.\end{cases}$$
三角形式：
$$x(t)=\tfrac12\sin(\pi t)+\sum_{\substack{n\ge1\\n\text{为奇数}}}\frac4{\pi(4-n^2)}\cos(n\pi t/2).$$`, r`系数定义是 $C_n=\frac14\int_0^2\sin(\pi t)e^{-jn\pi t/2}dt$。n≠±2时化为 $(1-e^{-jn\pi})/[\pi(4-n^2)]$；n=±2必须直接积分，不能拿0/0当零。直流积分为0，非1/π。b₂=1/2是保留的原正弦频率，其余bₙ为0。`, { minutes: 12, verified: 'corrected', note: '纸书第64页把n=±2复系数和所有正弦系数写成0，且在三角级数中加入无依据的1/π直流；直接积分得C₂=−j/4、C₋₂=j/4、直流0。' }),
  p('3.3(7)', ['3.2'], 'fourier-series', r`求 $x(t)=\sin^2t$ 的三角及复指数傅里叶级数，采用最小基本周期。`, r`$T_0=\pi,\omega_0=2$；$x=1/2-(1/2)\cos2t$，$C_0=1/2,C_{\pm1}=-1/4$，其余0。`, r`由倍角公式，平方把正弦正负半周变成重复波形，基本周期从2π减为π。若另选择非基本周期2π，也可将非零项记为C₊₂、C₋₂；两种展开都可，但应说明各自的基频。`, { minutes: 4, note: '原书以2π为展开周期并使用第2次谐波；这里按题干补充最小周期，未把合法的非基本周期展开判为错误。' }),
  p('3.4', ['3.2'], 'fourier-series', r`题图 3.4 为周期T>0、幅度E>0、占空比1/2的方波：$0<t<T/2$ 为E，$T/2<t<T$ 为0，周期延拓。求三角及复指数傅里叶级数。`, r`$\omega_0=2\pi/T,C_0=E/2$；
$$C_n=\frac{E[1-(-1)^n]}{j2\pi n}\ (n\ne0),\qquad x(t)=\frac E2+\frac{2E}\pi\sum_{\substack{n\ge1\\n\text{为奇数}}}\frac{\sin(n\omega_0t)}n.$$`, r`$C_n=\frac ET\int_0^{T/2}e^{-jn\omega_0t}dt$，指数必须含ω₀，积分上下限使 $e^{-jn\omega_0T/2}=(-1)^n$。余弦项为0，正弦项奇数阶为2E/(πn)。跳变处收敛到E/2。`, { ...pic('q3-4'), minutes: 9, verified: 'corrected', note: '纸书第64–65页解答忽略题图幅度E及基频ω₀，写成e^(−jnt)和cos(nt)；一般T下不成立，n=0还须单独算E/2。' }),
  p('3.5(a)', ['3.2'], 'fourier-series', r`题图 3.5(a)：周期4，$-1<t<1$ 为1，$1<t<3$ 为0，周期延拓。求复系数Cₙ并画频谱。`, r`$\omega_0=\pi/2,C_0=1/2$；$C_n=\sin(n\pi/2)/(n\pi)$（n≠0）。所有系数实偶，零谱线无相位。` + graph('a3-5-a'), r`$C_n=\frac14\int_{-1}^1e^{-jn\pi t/2}dt$。奇数阶谱线交替正负，非零偶数阶为0；C₀由平均值算得1/2。所画纵轴为有符号实系数Cₙ：若改画幅度，应对每项取绝对值，并给负系数相位π。FT冲激权重是2πCₙ。`, { ...pic('q3-5-a'), type: '画图', minutes: 9, verified: 'corrected', note: '纸书第65页系数公式正确，但第66页参考频谱漏了C₀=1/2并将离散谱线连成矩形边；重画包含直流与正负奇次线的级数谱。' }),
  p('3.5(b)', ['3.2'], 'fourier-series', r`题图 3.5(b)：周期T>0，一周期 $x(t)=E(1-t/T)$（0<t<T），E>0，周期延拓。求复系数并画幅度、相位谱。`, r`$\omega_0=2\pi/T,C_0=E/2$；$C_n=E/(j2\pi n)$（n≠0）。$|C_n|=E/(2\pi|n|)$，正频率相位−π/2、负频率π/2，直流相位0。` + graph('a3-5-b-mag') + graph('a3-5-b-phase'), r`按定义积分 $\frac1T\int_0^TE(1-t/T)e^{-jn\omega_0t}dt$，对n≠0分部积分，端点差给E/(jnω₀T)。均值要另算三角面积ET/2再除T，所以直流不含T。FT谱在同一位置有冲激，权重再乘2π。`, { ...pic('q3-5-b'), type: '画图', minutes: 10, verified: 'corrected', note: '纸书第66页推导的C₀=E/2正确，幅度图却标ET/2，误把面积当级数均值；按除以T后的系数重画。' }),
  p('3.6', ['3.2'], 'fourier-series', r`$x(t)=\cos2\pi t$ 的基本周期为1。若用T=3作为展开周期，求傅里叶级数系数，并说明展开基频与信号基频的区别。`, r`展开基频 $\Omega=2\pi/3$，$C_{\pm3}=1/2$、其他0；三角系数a₃=1、其他及直流0。信号的最小周期仍为1。`, r`原频率2π恰为3Ω。采用一个合法的非最小周期，只是给原频率换谐波下标，不会生成±1、±2分量，也不改变实际信号。`, { minutes: 4 }),
  p('3.7', ['3.2'], 'fourier-series', r`$x_1,x_2$ 的基本周期均为T，复系数分别为dₘ、eₘ。原题要求证明乘积也以T为“基波周期”，且 $c_k=\sum_m d_me_{k-m}$。证明系数公式，并检查“基波周期”是否一定成立。假定级数相乘换序合法，例如绝对收敛。`, r`T一定是乘积的一个周期，未必是最小基本周期；在可换序条件下
$$c_k=\sum_{m=-\infty}^{\infty}d_me_{k-m}.$$
反例：两个输入均为cos(2πt/T)，乘积cos²的基本周期为T/2。`, r`乘积 $\sum_m\sum_n d_me_ne^{j(m+n)\omega_0t}$，按k=m+n归组得到离散系数卷积，第二下标是k−m。也可由周期性直接看 $x_1(t+T)x_2(t+T)=x_1(t)x_2(t)$，这只证明T为一个周期；新频率可能只剩偶次谐波。无限级数不能在缺乏条件时任意逐项相乘、换序。`, { type: '分析', minutes: 8, verified: 'corrected', note: '纸书第67页把乘积的周期T断言为最小基波周期，cos²反例不成立；证明中后半的下标又从e_(k−m)改成e_(m−k)。保留正确系数卷积并修正周期断言。' }),
  p('3.8', ['3.2'], 'fourier-series', r`周期信号x(t)的复指数级数系数为Cₙ，$\omega_0=2\pi/T$。证明导数的系数为jnω₀Cₙ；说明有跳变时如何解释。`, r`$$D_n=jn\omega_0C_n.$$
连续可微的周期信号可用分部积分；有跳变时必须包含跳变冲激，按周期分布导数解释。`, r`$D_n=\frac1T\int_{t_0}^{t_0+T}x'(t)e^{-jn\omega_0t}dt$，分部积分的边界项因周期性相消，余项为jnω₀Cₙ。若x有跳变，其普通分段导数不包含全部导数，必须加每个跳变量对应的δ；例如周期锯齿的导数不是单纯常量。n=0的周期分布导数均值仍为0。`, { type: '分析', minutes: 6 }),
  p('3.9(a)', ['3.3'], 'ft-basic', r`题图3.9(a)：$x(t)=1$（0<t<τ，τ>0），其余0。按定义求FT，给零频极限。`, r`$$X(j\omega)=\frac{1-e^{-j\omega\tau}}{j\omega}=\tau\operatorname{Sa}(\omega\tau/2)e^{-j\omega\tau/2},\qquad X(0)=\tau.$$`, r`积分区间为0到τ。矩形中心在τ/2，不能用以0为中心的无相位矩形谱替代。零频值等于面积τ；公式中的0/0是可去奇点。`, { ...pic('q3-9-a'), minutes: 5 }),
  p('3.9(b)', ['3.3'], 'ft-basic', r`题图3.9(b)：$x(t)=E(1-t/T)$（0<t<T），其余0，T>0。按定义求FT，给零频极限。`, r`$$X(j\omega)=\frac{E}{j\omega}+\frac{E(1-e^{-j\omega T})}{T\omega^2},\qquad X(0)=ET/2.$$`, r`把积分写成 $E\int_0^Te^{-j\omega t}dt-\frac ET\int_0^Tte^{-j\omega t}dt$，分部积分后指数的1/(jω)项相消，得到所列两项。虽然各项单独在原点奇异，其和的极限有限并等于三角形面积。不要把这一个有限脉冲与3.5(b)的周期延拓混同。`, { ...pic('q3-9-b'), minutes: 7 }),
  p('3.10(1)', ['3.3', '3.4'], 'ft-basic', r`a>0、ω₀为实数，求 $e^{-at}\cos(\omega_0t)u(t)$ 的FT。`, r`$$X(j\omega)=\tfrac12\left[\frac1{a+j(\omega-\omega_0)}+\frac1{a+j(\omega+\omega_0)}\right]=\frac{a+j\omega}{(a+j\omega)^2+\omega_0^2}.$$`, r`将余弦拆成两复指数，两个分母各移jω₀。合并后的分母为 $(a+j\omega-j\omega_0)(a+j\omega+j\omega_0)$，应加ω₀²。ω₀=0回到普通衰减指数；a>0保证绝对收敛。`, { minutes: 6, verified: 'corrected', note: '纸书第68页移频分母漏了ω₀前的j，合并分母误为减ω₀²；按两复指数积分修正为加ω₀²。' }),
  p('3.10(2)', ['3.3'], 'ft-basic', r`求 $x(t)=e^{-3t}[u(t+2)-u(t-3)]$ 的FT。`, r`$$X(j\omega)=\frac{e^{2(3+j\omega)}-e^{-3(3+j\omega)}}{3+j\omega}.$$`, r`截断区间是−2<t<3，直接积分 $\int_{-2}^3e^{-(3+j\omega)t}dt$。不要将左端−2误改为0，也不能替换为同宽的e⁻²ᵗ变式。零频值为(e⁶−e⁻⁹)/3。`, { minutes: 5 }),
  p('3.10(3)', ['3.3', '3.4'], 'ft-property', r`求 $te^{-2t}\sin4t\,u(t)$ 的FT。`, r`$$X(j\omega)=\frac1{2j}\left[\frac1{(2+j\omega-4j)^2}-\frac1{(2+j\omega+4j)^2}\right]=\frac{8(2+j\omega)}{[(2+j\omega)^2+16]^2}.$$`, r`先对e⁻²ᵗu乘t，得到1/(2+jω)²，再用正弦移频。或者对e⁻²ᵗsin4t·u的谱4/[(2+jω)²+16]求j倍导数，乘积与链式求导给相同结果。`, { minutes: 7 }),
  p('3.10(4)', ['3.3'], 'ft-basic', r`求全时间信号 $\sin t+\cos(2\pi t+\pi/4)$ 的广义FT。`, r`$$X(j\omega)=\frac\pi j[\delta(\omega-1)-\delta(\omega+1)]+\pi e^{j\pi/4}\delta(\omega-2\pi)+\pi e^{-j\pi/4}\delta(\omega+2\pi).$$`, r`每个永久复指数的FT是2π倍冲激；正弦的两条权重相反，移相余弦的两条权重共轭。这里两个物理频率比2π是无理数，整体不是周期信号，但仍有离散广义谱，不能用通常“非周期必连续”的简化断言。`, { minutes: 6 }),
  p('3.10(5)', ['3.3', '3.4'], 'ft-property', r`求 $x(t)=\sin t\sin2t/t^2$ 的FT，t=0按连续极限取值。`, r`$$X(j\omega)=\begin{cases}\pi,&|\omega|\le1,\\\frac\pi2(3-|\omega|),&1<|\omega|<3,\\0,&|\omega|\ge3.\end{cases}$$`, r`sin t/t和sin2t/t分别对应高度π、半宽1与2的矩形谱。时域乘积给频谱卷积除2π，重叠宽度在|ω|≤1为2，在1<|ω|<3为3−|ω|，因此是平台π的梯形。原点时间值为2，也可从谱面积4π除2π回算。`, { minutes: 8 }),
  p('3.10(6)', ['3.3', '3.4'], 'ft-property', r`求 $x(t)=\int_{-\infty}^t\sin(\pi\tau)/(\pi\tau)d\tau$ 的广义FT。`, r`$$X(j\omega)=\mathbf1_{|\omega|<\pi}\operatorname{PV}\frac1{j\omega}+\pi\delta(\omega).$$`, r`被积信号的谱Q在|ω|<π为1，且Q(0)=1。累计积分是与u卷积，按 $\mathcal F\{u\}=\operatorname{PV}(1/j\omega)+\pi\delta$ 得上式。累计函数在±∞分别趋0、1，故存在直流广义项；不能仅除jω而漏πδ。原点x(0)=1/2。`, { minutes: 7 }),
  p('3.12(a)', ['3.4'], 'ft-property', r`题图3.12(a)：$x(t)=t/\tau$（|t|<τ），其余0，τ>0。用微积分性质求FT，保留截断点跳变。`, r`$$X(j\omega)=\frac{2j[\omega\tau\cos(\omega\tau)-\sin(\omega\tau)]}{\omega^2\tau},\qquad X(0)=0.$$`, r`分布导数为 $x'=\tau^{-1}[u(t+\tau)-u(t-\tau)]-\delta(t+\tau)-\delta(t-\tau)$。两端的跳变量都是−1，因而 $j\omega X=2\operatorname{Sa}(\omega\tau)-2\cos(\omega\tau)$。信号实奇，谱应纯虚奇；原点值通过面积或极限为0。`, { ...pic('q3-12-a'), minutes: 8 }),
  p('3.12(b)', ['3.4'], 'ft-property', r`题图3.12(b)：中心对称梯形，|t|≤τ₁/2为E，在τ₁/2<|t|<τ₂/2线性降至0，带外0；$0\le\tau_1<\tau_2,E>0$。用微积分性质求FT。`, r`$$X(j\omega)=\frac{4E[\cos(\omega\tau_1/2)-\cos(\omega\tau_2/2)]}{(\tau_2-\tau_1)\omega^2},\qquad X(0)=E(\tau_1+\tau_2)/2.$$`, r`斜率跳变给 $x''=\frac{2E}{\tau_2-\tau_1}[\delta(t+\tau_2/2)+\delta(t-\tau_2/2)-\delta(t+\tau_1/2)-\delta(t-\tau_1/2)]$。除以(jω)²时负号将余弦次序反转。另可视作宽度(τ₁+τ₂)/2与(τ₂−τ₁)/2的两矩形卷积，再乘2E/(τ₂−τ₁)。`, { ...pic('q3-12-b'), minutes: 9 }),
  p('3.15', ['3.4'], 'ft-property', r`实信号x(t)的FT为 $X=A+jB$，A、B为实函数。令xₑ、xₒ为时域偶部、奇部，证明它们分别对应A、jB。`, '$x_e\leftrightarrow A$，$x_o\leftrightarrow jB$；A实偶，B实奇。', r`实时域信号的共轭对称为 $X(-\omega)=X^*(\omega)=A(\omega)-jB(\omega)$。取x(t)与x(−t)的半和、半差，谱相应变为[X(ω)+X(−ω)]/2=A与半差jB。只有在x为实信号时才能把频域实虚部直接与时域奇偶部分这样对应。`, { type: '分析', minutes: 6 }),
  p('3.16', ['3.4'], 'ft-property', r`已知 $x_1(t)\leftrightarrow X_1(j\omega)$，求 $x_2(t)=\int_{-\infty}^t x_1[2(\tau-1)]d\tau$ 的频谱。假定x₁可积、相关广义运算存在。`, r`$$X_2(j\omega)=\tfrac12e^{-j\omega}X_1(j\omega/2)\operatorname{PV}\frac1{j\omega}+\tfrac\pi2X_1(0)\delta(\omega).$$`, r`缩放加延时的被积信号g=x₁[2(t−1)]，$G=\frac12e^{-j\omega}X_1(j\omega/2)$。累计积分给G乘阶跃谱，δ系数只取G(0)=X₁(0)/2，不能把非零频率的相位因子带进δ权重。`, { minutes: 8 }),
  p('3.17(1)', ['3.3', '3.4'], 'ft-property', r`ω₀>0，利用频域卷积定理求 $\cos(\omega_0t)u(t)$ 的广义FT。`, r`$$X=\frac12\left[\operatorname{PV}\frac1{j(\omega-\omega_0)}+\operatorname{PV}\frac1{j(\omega+\omega_0)}\right]+\frac\pi2[\delta(\omega-\omega_0)+\delta(\omega+\omega_0)].$$`, r`全时间余弦的谱π[δ(ω−ω₀)+δ(ω+ω₀)]与阶跃谱卷积，并除2π；两冲激各将阶跃谱平移。不能写成普通ω₀²−ω²分式而丢掉主值及谱线。`, { minutes: 7 }),
  p('3.17(2)', ['3.3', '3.4'], 'ft-property', r`ω₀>0，利用频域卷积定理求 $\sin(\omega_0t)u(t)$ 的广义FT。`, r`$$X=\frac1{2j}\left[\operatorname{PV}\frac1{j(\omega-\omega_0)}-\operatorname{PV}\frac1{j(\omega+\omega_0)}\right]+\frac\pi{2j}[\delta(\omega-\omega_0)-\delta(\omega+\omega_0)].$$`, r`全时间正弦谱(π/j)[δ(ω−ω₀)−δ(ω+ω₀)]与阶跃谱卷积，得到两次平移的差。正频率δ系数为−jπ/2，负频率为+jπ/2；远离谱线的普通部分为ω₀/(ω₀²−ω²)。`, { minutes: 7 }),
  p('3.18(1)', ['2.4', '3.4'], 'conv-integral', conv + '画x₁*x₂的图，给分段式。', r`令 $a=(\tau_1+\tau_2)/2,b=|\tau_1-\tau_2|/2,m=\min(\tau_1,\tau_2)$，则
$$y(t)=E_1E_2\begin{cases}m,&|t|\le b,\\a-|t|,&b<|t|<a,\\0,&|t|\ge a.\end{cases}$$` + graph('a3-18-1'), r`直接卷积是区间[−τ₁/2,τ₁/2]与[t−τ₂/2,t+τ₂/2]的重叠长度乘E₁E₂。较窄矩形全落入较宽矩形时达到平台m；边缘部分重叠长度a−|t|。等宽时b=0，平台退化成顶点，图为三角形。参数对调不会改变答案。`, { ...pic('q3-18'), type: '画图', minutes: 8 }),
  p('3.18(2)', ['3.4'], 'ft-property', conv + '求x₁*x₂的频谱。', r`$$Y(j\omega)=E_1E_2\tau_1\tau_2\operatorname{Sa}(\omega\tau_1/2)\operatorname{Sa}(\omega\tau_2/2).$$`, r`时域卷积在频域直接相乘，不带1/(2π)；那个因子属于时域乘积对应频谱卷积。检查Y(0)=E₁E₂τ₁τ₂，等于卷积总面积，也等于两个矩形面积的乘积。`, { ...pic('q3-18'), minutes: 5 }),
  p('3.19', ['3.3'], 'ft-basic', r`题图3.19：x(t)在0<t<1为2，在1<t<2为1，其余0。求FT及零频值。`, r`$$X(j\omega)=\frac{2-e^{-j\omega}-e^{-2j\omega}}{j\omega},\qquad X(0)=3.$$`, r`分两段积分，$2\int_0^1e^{-j\omega t}dt+\int_1^2e^{-j\omega t}dt$。也可将信号分解成宽度2和宽度1、均从0开始的两个单位矩形。原点频谱是面积2+1=3。`, { ...pic('q3-19'), minutes: 5 }),
  p('3.22', ['3.2', '3.5'], 'fourier-series', r`题图3.22：正单位冲激在nT，负单位冲激在nT+T/2，n为任意整数，T>0。求周期冲激列的频谱函数，区分级数系数与FT。`, r`$\omega_0=2\pi/T$，$C_n=[1-(-1)^n]/T$；偶数阶为0，奇数阶为2/T。广义FT为
$$X(j\omega)=\frac{4\pi}T\sum_{\substack{n\in\mathbb Z\\n\text{为奇数}}}\delta(\omega-n\omega_0).$$` + graph('a3-22'), r`选取不将冲激放在端点的完整周期区间，比如(−T/4,3T/4)。筛选两个冲激得[1−e⁻ʲⁿπ]/T，不产生半值端点歧义。半周期平移使符号反转，不是基本周期T/2。书中图的2/T是级数系数，并非FT冲激权重。`, { ...pic('q3-22'), type: '画图', minutes: 8, note: '原书第78页画的是Cₙ谱线，题目所问频谱函数另需乘2π；两种口径均明确列出。' }),
  p('3.23', ['3.3', '3.4'], 'ft-property', r`题图3.23：|X(jω)|在|ω|<ω₀为A，带外0；相位在−ω₀<ω<0为+A，0<ω<ω₀为−A。A>0、ω₀>0，图中幅度和相位参数均用同一个A。求逆FT。`, r`$$x(t)=\frac{A[\sin(\omega_0t-A)+\sin A]}{\pi t}=\frac{A\omega_0}\pi\operatorname{Sa}(\omega_0t/2)\cos(\omega_0t/2-A),\qquad x(0)=\frac{A\omega_0\cos A}\pi.$$`, r`负频谱为Aeʲᴬ，正频谱为Ae⁻ʲᴬ，互为共轭，逆变换是实函数。分别在(−ω₀,0)、(0,ω₀)积分，合并为 $\frac A\pi\int_0^{\omega_0}\cos(\omega t-A)d\omega$。两指数相加等于2cos，不能漏掉2。带外相位无意义，单点ω=0的定义不改变积分。`, { ...pic('q3-23'), minutes: 9, verified: 'corrected', note: '纸书第79页最后一行将两共轭指数之和改写余弦时漏了因子2，结果只有正确幅度的一半；在t=0按原谱直接积分也能检出。' }),
  p('3.24(1)', ['3.3'], 'ft-basic', r`已知 $X(j\omega)=\delta(\omega-\omega_0)$，求逆FT。`, r`$$x(t)=\frac{e^{j\omega_0t}}{2\pi}.$$`, r`逆积分的冲激筛选给eʲω₀t，再乘1/(2π)。只有正频率冲激，所以输出是复指数；不能擅自取余弦或加负频率。`, { minutes: 3 }),
  p('3.24(2)', ['3.3'], 'ft-basic', r`已知 $X(j\omega)=\delta(\omega+\omega_0)-\delta(\omega-\omega_0)$，求逆FT。`, r`$$x(t)=-\frac j\pi\sin(\omega_0t)=\frac{\sin(\omega_0t)}{j\pi}.$$`, r`逆变换给 $(e^{-j\omega_0t}-e^{j\omega_0t})/(2\pi)$。这是实奇频谱，对应纯虚奇时间信号。频谱不满足共轭偶对称，不能认为时间信号为实正弦。`, { minutes: 4 }),
  p('3.24(3)', ['3.3'], 'ft-basic', r`ω₀>0，已知 $X(j\omega)=u(\omega+\omega_0)-u(\omega-\omega_0)$，求逆FT。`, r`$$x(t)=\frac{\sin(\omega_0t)}{\pi t},\qquad x(0)=\omega_0/\pi.$$`, r`在−ω₀到ω₀积分eʲωt并乘1/(2π)。频谱为中心单位矩形，输出实偶；谱边缘普通单点不改变逆积分。`, { minutes: 4 }),
  p('3.24(4)', ['3.3', '3.4'], 'ft-property', r`原题分段谱第一行印 $X(j\omega)=\omega/\pi,\ \omega\le\omega_0$，第二行印 $X=0,\ |\omega|>\omega_0$（ω₀>0），条件在负频率处互相冲突。说明问题，并按原解答采用的 $|\omega|\le\omega_0$ 有限频带解释求逆FT。`, r`按明确的有限频带解释，
$$x(t)=\frac{j[\sin(\omega_0t)-\omega_0t\cos(\omega_0t)]}{\pi^2t^2},\qquad x(0)=0.$$
原分段条件按字面不定义唯一频谱，不能无条件作此解。`, r`有限频带内X=ω/π，带外0。先反演单位矩形Q得q=sin(ω₀t)/(πt)，再用ωQ↔q′/j，乘1/π得到上式。它为纯虚奇函数，与实奇谱相符。原书第79页第一分段在ω<−ω₀仍满足ω≤ω₀，却同时满足带外条件，必须说明修正解释。`, { minutes: 9, verified: 'uncertain', note: '纸书第79页第一条件漏绝对值，与第二条件重叠且给不同值；有限带解是参考解采用的条件解释，排除自动组卷及808能力证据。' }),
  p('3.25(1)', ['3.3', '3.4'], 'ft-property', r`求 $X(j\omega)=1/(2+j\omega)^2$ 的逆FT。`, r`$$x(t)=te^{-2t}u(t).$$`, r`e⁻²ᵗu↔1/(2+jω)，按乘t性质 $j\frac d{d\omega}[1/(2+j\omega)]=1/(2+j\omega)^2$。也可将两个e⁻²ᵗu卷积，从0到t积分得到te⁻²ᵗu。此题为FT反演，不混同需ROC的双边拉普拉斯反演。`, { minutes: 5 }),
  p('3.25(2)', ['3.3', '3.4'], 'ft-property', r`原题只给 $X(j\omega)=-2/\omega^2$，求逆FT。说明原点的广义解释为何不可省，检查原解答2tu(t)。`, r`若明确取标准有限部 $X=-2\operatorname{Fp}(1/\omega^2)$，则 $x(t)=|t|$。因果斜坡的完整广义谱是
$$\mathcal F\{2tu(t)\}=-2\operatorname{Fp}(1/\omega^2)+2j\pi\delta'(\omega).$$
仅给ω≠0处的分式不能确定原点分布项，也不能唯一反演。`, r`普通1/ω²在0附近不可积，Cauchy对称主值也发散，需有限部或其他明确正则化。对u的完整谱求2j倍导数：有限部项之外产生2jπδ′。|t|=2tu(t)−t，而t↔2jπδ′，两者普通非零频率部分相同但完整分布不同。不能简单把衰减参数置0而省去边界分布。`, { type: '分析', minutes: 10, verified: 'uncertain', note: '纸书第80页把衰减率直接置0得到2tu(t)，漏掉2jπδ′；原题未指定原点广义延拓。提供有限部条件解和斜坡完整谱，排除自动组卷与808能力证据。' }),
  p('3.27(1)', ['3.7', '2.3'], 'ft-property', allpass + '求单位阶跃响应g(t)。', r`$$g(t)=(1-2e^{-t})u(t).$$`, r`H=−1+2/(1+jω)，因此h=−δ+2e⁻ᵗu。与u卷积给−u+2(1−e⁻ᵗ)u。g(0⁺)=−1、终值1，直通−δ导致阶跃输出立即跳到负值；积分h时必须保留它。`, { minutes: 7 }),
  p('3.27(2)', ['3.7', '3.3'], 'ft-property', allpass + r`输入 $e^{-2t}u(t)$，求零状态响应。`, r`$$y_{zs}(t)=(2e^{-t}-3e^{-2t})u(t).$$`, r`输入谱1/(2+jω)，相乘后 $Y=2/(1+j\omega)-3/(2+j\omega)$。或在时域求−x+2e⁻ᵗu*x。输出右值−1，直接项取输入右值的负号，不能误把严格真分式系统的右值0套在本题。`, { minutes: 7 }),
  p('3.28', ['3.7', '3.8'], 'sine-steady', r`LTI系统频率响应 $H(j\omega)=1/(1+j\omega)$，全时间周期输入 $x(t)=\sin t+\sin3t$。求零状态响应，画输入与输出波形，并讨论是否失真。`, r`$$y(t)=\frac1{\sqrt2}\sin(t-\pi/4)+\frac1{\sqrt{10}}\sin(3t-\arctan3).$$
两个频率的幅度衰减不同，无法写成同一常数倍的x(t−t₀)，因此对该输入有失真。` + graph('a3-28'), r`H(j)=(1−j)/2，H(j3)=(1−3j)/10，分子相位0，分母相位分别atan1、atan3。以 $y=(\sin t-\cos t)/2+(\sin3t-3\cos3t)/10$ 画同一纵轴的两曲线。输入未乘u(t)，不额外添加t=0开通暂态。对本输入，仅不同的非零频率增益就足以否定无失真，不依赖对整个频带群延迟的模糊论述。`, { type: '画图', minutes: 11, verified: 'corrected', note: '纸书第81页把第二分量的相位写为π/2−atan3，分子为1而非j，没有π/2；正确为−atan3。保留原全时间输入并重画。' }),
  p('3.29', ['3.7', '2.1', '2.2'], 'ode-s-solve', r`系统 $H(j\omega)=j\omega/(-\omega^2+5j\omega+6)$，原初态 $y(0^-)=2,y'(0^-)=1$，输入 $e^{-t}u(t)$。按对应二阶方程求t≥0的完全响应。`, r`$$y(t)=-\tfrac12e^{-t}+9e^{-2t}-\tfrac{13}2e^{-3t},\qquad t\ge0.$$`, r`对应 $y''+5y'+6y=x'$。零输入由左初值得7e⁻²ᵗ−5e⁻³ᵗ；零状态谱 $s/[(s+1)(s+2)(s+3)]$，反演为(−e⁻ᵗ/2+2e⁻²ᵗ−3e⁻³ᵗ/2)u，两者相加。输入微分含强度1的δ，故y右值仍2，右导数从1跳至2。完全响应中的观察段不能被当成对全时间非零初态的零延拓。`, { minutes: 12, note: '初态是0−，不同于给同一H但指定0+导数的变式；不合并为同题。' }),
  p('3.30', ['3.7', '2.1', '2.3'], 'ode-s-solve', r`LTI系统方程 $y''+4y'+3y=x'+2x$。求频率响应H(jω)和单位冲激响应h(t)，采用频率响应存在的卷积型零状态系统。`, r`$$H(j\omega)=\frac{j\omega+2}{(j\omega+1)(j\omega+3)}=\frac1{2(j\omega+1)}+\frac1{2(j\omega+3)},\qquad h(t)=\tfrac12(e^{-t}+e^{-3t})u(t).$$`, r`频域微分分别乘jω，交叉相除得到H；部分分式两系数都是+1/2。原点h(0⁺)=1，h′(0⁺)=−2，回代分布方程给δ′+2δ。仅求h的2.19(1)少一项明确要求H的完整作答任务，保留为不同要求。`, { minutes: 8, verified: 'corrected', note: '纸书第82页部分分式误为一正一负，最后两个指数又同时印e^(−3t)，使h误成0；按原方程回算修正为两项相加。' }),
  p('3.31', ['3.6', '3.9'], 'filter-output', r`输入 $x(t)=8\cos100t\cos500t$，先与 $s(t)=\cos500t$ 相乘，再通过 $H(j\omega)=u(\omega+120)-u(\omega-120)$。求输出。`, r`$$y(t)=4\cos100t.$$`, r`乘法器后 $8\cos100t\cos^2500t=4\cos100t+2\cos900t+2\cos1100t$，截止120rad/s的单位低通只通过100分量。不能漏掉第二次乘余弦的1/2幅度因子。`, { minutes: 7 }),
  p('3.32(1)', ['3.7', '3.4'], 'filter-output', lp + '求冲激响应。', r`$$h(t)=\frac{\sin[2\pi(t-2)]}{\pi(t-2)},\qquad h(2)=2.$$`, r`单位矩形谱半宽2π的逆FT为sin(2πt)/(πt)，再由e⁻ʲ²ω产生整体延时2。原点是相对t−2的可去点，按极限取2；理想延时低通仍有负时间尾部。`, { minutes: 6 }),
  p('3.32(2)', ['3.7', '3.4'], 'filter-output', lp + r`输入 $x(t)=\mathrm{Sa}(\pi t)$，求输出。`, r`$$y(t)=\frac{\sin[\pi(t-2)]}{\pi(t-2)},\qquad y(2)=1.$$`, r`输入谱在|ω|<π为1，全部位于滤波通带，故只延时2，幅度不变。Sa的归一化定义必须明确；本题不是sin(πt)/t。`, { minutes: 5 }),
  p('3.32(3)', ['3.7', '3.4'], 'filter-output', lp + r`输入 $x(t)=\mathrm{Sa}(3\pi t)$，求输出。`, r`$$y(t)=\frac{\sin[2\pi(t-2)]}{3\pi(t-2)},\qquad y(2)=2/3.$$`, r`输入矩形谱在|ω|<3π内高度1/3。低通将半宽截到2π，但保留高度1/3，再产生延时2；不能把带宽截断同时误认为频谱高度恢复为1。`, { minutes: 6 }),
];
