import { test, expect } from '@playwright/test';
import { resolve } from 'node:path';

const eventsKey = 'trainer808.events.v1';
const settingsKey = 'trainer808.settings.v1';
const base = (process.env.PLAYWRIGHT_BASE_URL ?? 'http://127.0.0.1:18080').replace(/\/$/, '');
const result = { transcript: '$4\\times 1=4$', steps: [{ step: '取极限', ok: false, comment: '极限应为2' }], grade: 1, tags: ['计算失误'], feedback: '检查系数' };

test('Gemini文字结果在手机导入，先核题号、预填、人工改分，再保存并统计', async ({ page, context }) => {
  let gradeCalls = 0;
  await context.route('**/api/health', route => route.fulfill({ json: { ok: true, ai: false, sync: false, model: '' } }));
  await context.route('**/api/grade', route => { gradeCalls++; return route.fulfill({ status: 503, json: { error: '测试不使用真实模型' } }); });
  await page.setViewportSize({ width: 375, height: 812 });
  await page.goto(base + '/#/p/tk-key-1-2');
  const panel = page.locator('.ai-panel');
  await expect(panel.getByRole('link', { name: '打开 Gemini' })).toHaveAttribute('href', 'https://gemini.google.com/app');
  await panel.locator('summary').click();
  const input = panel.getByLabel('批改结果 JSON');
  await input.fill(JSON.stringify({ ...result, problemId: 'zt2026-10' }));
  await panel.getByRole('button', { name: '读取批改结果' }).click();
  await expect(panel.getByRole('status')).toContainText('未读取到本题');
  expect(await page.evaluate(key => JSON.parse(localStorage.getItem(key) ?? '[]'), eventsKey)).toHaveLength(0);
  await input.fill('```json\n' + JSON.stringify({ ...result, problemId: 'tk-key-1-2', score: 100 }) + '\n```');
  await panel.getByRole('button', { name: '读取批改结果' }).click();
  await expect(panel.getByText('AI 建议：部分对', { exact: true })).toBeVisible();
  await expect(panel).not.toContainText('估分');
  await expect(page.locator('.grade.g1')).toHaveClass(/on/);
  await panel.screenshot({ path: 'work/screenshots/grading-fallback-mobile.png' });
  expect(await page.evaluate(key => JSON.parse(localStorage.getItem(key) ?? '[]'), eventsKey)).toHaveLength(0);
  await expect(page.getByRole('button', { name: '记录', exact: true })).toBeDisabled();
  await panel.getByLabel('转写复核').selectOption('checked');
  await page.getByRole('button', { name: '大部分对', exact: true }).click();
  await page.getByRole('button', { name: '记录', exact: true }).click();
  const saved = await page.evaluate(key => JSON.parse(localStorage.getItem(key) ?? '[]'), eventsKey);
  expect(saved).toHaveLength(1);
  expect(saved[0]).toMatchObject({ grade: 2, ai: { grade: 1, model: 'Gemini（手动导入）' }, recognition: { status: 'checked' } });
  expect(saved[0].ai).not.toHaveProperty('score');
  expect(JSON.stringify(saved)).not.toContain('data:image');
  await expect(input).toBeDisabled();
  expect(gradeCalls).toBe(0);
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(376);
  await page.goto(base + '/#/settings');
  const audit = page.locator('.grading-audit');
  await expect(audit).toContainText('Gemini（手动导入）：1 条，调整评分 1 条');
  await expect(audit).toContainText('不能当作模型的识别准确率');
  await audit.screenshot({ path: 'work/screenshots/grading-audit-mobile.png' });
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(376);
});

test('换照片后批改失败，不沿用上一张的AI建议或评分', async ({ page, context }) => {
  await context.route('**/api/health', route => route.fulfill({ json: { ok: true, ai: true, sync: false, model: 'vision-mock' } }));
  await page.addInitScript(key => localStorage.setItem(key, JSON.stringify({ aiEnabled: true, syncKey: 'test-sync-only' })), settingsKey);
  let calls = 0;
  await context.route('**/api/grade', route => {
    calls++;
    return calls === 1 ? route.fulfill({ json: { choices: [{ message: { content: JSON.stringify({ ...result, grade: 3, tags: [] }) } }] } }) : route.fulfill({ status: 502, json: { error: '测试模型临时忙碌' } });
  });
  await page.goto(base + '/#/p/zt2026-10');
  const panel = page.locator('.ai-panel');
  await panel.getByLabel('作答照片').setInputFiles(resolve('tests/fixtures/blank.png'));
  await panel.getByRole('button', { name: '开始 AI 批改', exact: true }).click();
  await expect(panel.getByText('AI 建议：全对', { exact: true })).toBeVisible();
  await panel.getByLabel('作答照片').setInputFiles(resolve('tests/fixtures/blank.png'));
  await expect(panel.getByText(/^AI 建议：/)).toHaveCount(0);
  await expect(page.getByRole('button', { name: '记录', exact: true })).toBeDisabled();
  await panel.getByRole('button', { name: '开始 AI 批改', exact: true }).click();
  await expect(panel.getByRole('status')).toContainText('测试模型临时忙碌');
  await expect(panel.locator('details.external-grade')).toHaveAttribute('open', '');
  await expect(page.getByRole('button', { name: '记录', exact: true })).toBeDisabled();
  await page.getByRole('button', { name: '不会', exact: true }).click();
  await page.getByRole('button', { name: '记录', exact: true }).click();
  const saved = await page.evaluate(key => JSON.parse(localStorage.getItem(key) ?? '[]'), eventsKey);
  expect(saved).toHaveLength(1); expect(saved[0].grade).toBe(0); expect(saved[0]).not.toHaveProperty('ai');
  expect(calls).toBe(2);
});

test('忽略看不清的AI转写后，手动评分不携带原建议', async ({ page, context }) => {
  await context.route('**/api/health', route => route.fulfill({ json: { ok: true, ai: false, sync: false, model: '' } }));
  await page.goto(base + '/#/p/zt2026-10');
  const panel = page.locator('.ai-panel');
  await panel.locator('summary').click();
  await panel.getByLabel('批改结果 JSON').fill(JSON.stringify({ ...result, problemId: 'zt2026-10', transcript: '[看不清]' }));
  await panel.getByRole('button', { name: '读取批改结果' }).click();
  await expect(panel.getByText('AI 建议：部分对', { exact: true })).toBeVisible();
  await panel.getByRole('button', { name: '忽略 AI 建议' }).click();
  await expect(page.getByRole('button', { name: '记录', exact: true })).toBeDisabled();
  await page.getByRole('button', { name: '全对', exact: true }).click();
  await page.getByRole('button', { name: '记录', exact: true }).click();
  const saved = await page.evaluate(key => JSON.parse(localStorage.getItem(key) ?? '[]'), eventsKey);
  expect(saved[0].grade).toBe(3); expect(saved[0]).not.toHaveProperty('ai');
  await page.goto(base + '/#/settings');
  await expect(page.locator('.grading-audit')).toContainText('暂无已确认的辅助批改记录');
});

test('先修正手写公式，再按实际作答评分；原建议和修正记录各自保存', async ({ page, context }) => {
  await context.route('**/api/health', route => route.fulfill({ json: { ok: true, ai: false, sync: false, model: '' } }));
  await page.setViewportSize({ width: 375, height: 812 });
  await page.goto(base + '/#/p/zt2026-10');
  const panel = page.locator('.ai-panel');
  await panel.locator('summary').click();
  await panel.getByLabel('批改结果 JSON').fill(JSON.stringify({ ...result, problemId: 'zt2026-10', transcript: '$y(t)=-10u(t)$' }));
  await panel.getByRole('button', { name: '读取批改结果' }).click();
  await expect(page.getByRole('button', { name: '记录', exact: true })).toBeDisabled();
  await panel.getByLabel('转写复核').selectOption('corrected');
  await expect(page.locator('.grade.g1')).not.toHaveClass(/on/);
  await page.getByRole('button', { name: '全对', exact: true }).click();
  await expect(page.getByRole('button', { name: '记录', exact: true })).toBeDisabled();
  await panel.getByLabel('修正后的转写').fill('$y(t)=10u(t)$');
  await expect(page.getByRole('button', { name: '记录', exact: true })).toBeDisabled();
  await expect(page.locator('.grade.g3')).not.toHaveClass(/on/);
  await page.getByRole('button', { name: '全对', exact: true }).click();
  expect(await page.evaluate(key => JSON.parse(localStorage.getItem(key) ?? '[]'), eventsKey)).toHaveLength(0);
  await panel.screenshot({ path: 'work/screenshots/grading-correction-mobile.png' });
  await page.getByRole('button', { name: '记录', exact: true }).click();
  const saved = await page.evaluate(key => JSON.parse(localStorage.getItem(key) ?? '[]'), eventsKey);
  expect(saved).toHaveLength(1);
  expect(saved[0]).toMatchObject({ grade: 3, tags: [], ai: { grade: 1, transcript: '$y(t)=-10u(t)$' }, recognition: { status: 'corrected', transcript: '$y(t)=10u(t)$' } });
  await expect(panel.getByLabel('修正后的转写')).toBeDisabled();
  await page.goto(base + '/#/settings');
  const audit = page.locator('.grading-audit');
  await expect(audit).toContainText('转写复核 1 条，其中修正 1 条、照片看不清 0 条');
  await audit.screenshot({ path: 'work/screenshots/grading-correction-audit-mobile.png' });
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(376);
});

test('照片看不清时清除预填评分，按纸上实际作答自评后记录复核情况', async ({ page, context }) => {
  await context.route('**/api/health', route => route.fulfill({ json: { ok: true, ai: false, sync: false, model: '' } }));
  await page.goto(base + '/#/p/zt2026-10');
  const panel = page.locator('.ai-panel');
  await panel.locator('summary').click();
  await panel.getByLabel('批改结果 JSON').fill(JSON.stringify({ ...result, problemId: 'zt2026-10', transcript: '[看不清]', grade: 3, tags: [] }));
  await panel.getByRole('button', { name: '读取批改结果' }).click();
  await panel.getByLabel('转写复核').selectOption('unreadable');
  await expect(page.locator('.grade.g3')).not.toHaveClass(/on/);
  await expect(page.getByRole('button', { name: '记录', exact: true })).toBeDisabled();
  await page.getByRole('button', { name: '不会', exact: true }).click();
  await page.locator('label.tag').filter({ hasText: '方法不会' }).click();
  await page.getByRole('button', { name: '记录', exact: true }).click();
  const saved = await page.evaluate(key => JSON.parse(localStorage.getItem(key) ?? '[]'), eventsKey);
  expect(saved[0]).toMatchObject({ grade: 0, tags: ['方法不会'], recognition: { status: 'unreadable' } });
  await page.goto(base + '/#/settings');
  await expect(page.locator('.grading-audit')).toContainText('转写复核 1 条，其中修正 0 条、照片看不清 1 条');
});

test('模拟卷重新评分清除上次批改，保留旧复核记录且新自评能保存', async ({ page, context }) => {
  await context.route('**/api/health', route => route.fulfill({ json: { ok: true, ai: false, sync: false, model: '' } }));
  await page.goto(base + '/#/mock');
  await page.getByRole('button', { name: '保存并开始模拟卷', exact: true }).click();
  const start = await page.evaluate(key => JSON.parse(localStorage.getItem(key) ?? '[]').find((e: { kind: string; action?: string }) => e.kind === 'exam' && e.action === 'start'), eventsKey);
  const panel = page.locator('.ai-panel');
  await panel.locator('summary').click();
  await panel.getByLabel('批改结果 JSON').fill(JSON.stringify({ ...result, problemId: start.items[0].problemId }));
  await panel.getByRole('button', { name: '读取批改结果' }).click();
  await panel.getByLabel('转写复核').selectOption('checked');
  await page.getByRole('button', { name: '记录', exact: true }).click();
  await page.getByRole('button', { name: '重新评分', exact: true }).click();
  await expect(panel.getByText(/^AI 建议：/)).toHaveCount(0);
  await expect(panel.getByLabel('转写复核')).toHaveCount(0);
  await page.getByRole('button', { name: '全对', exact: true }).click();
  await page.getByRole('button', { name: '记录', exact: true }).click();
  const attempts = await page.evaluate(key => JSON.parse(localStorage.getItem(key) ?? '[]').filter((e: { kind: string }) => e.kind === 'attempt'), eventsKey);
  expect(attempts).toHaveLength(2);
  expect(attempts[0]).toMatchObject({ recognition: { status: 'checked' }, ai: { grade: 1 } });
  expect(attempts[1]).toMatchObject({ grade: 3, examId: start.examId });
  expect(attempts[1]).not.toHaveProperty('ai');
  expect(attempts[1]).not.toHaveProperty('recognition');
});

test('带图题批改附上题图及PNG化的SVG答案图，三张图各自标注用途', async ({ page, context }) => {
  await context.route('**/api/health', route => route.fulfill({ json: { ok: true, ai: true, sync: false, model: 'gemini-3.8-flash' } }));
  await page.addInitScript(key => localStorage.setItem(key, JSON.stringify({ aiEnabled: true, syncKey: 'test-sync-only' })), settingsKey);
  let received: { model: string; messages: { content: { type: string; text?: string; image_url?: { url: string } }[] }[] } | undefined;
  await context.route('**/api/grade', route => {
    received = route.request().postDataJSON();
    return route.fulfill({ json: { choices: [{ message: { content: JSON.stringify(result) } }] } });
  });
  await page.setViewportSize({ width: 375, height: 812 });
  await page.goto(base + '/#/p/wmq6-6-20-2a');
  const panel = page.locator('.ai-panel');
  await expect(panel).toContainText('1 张题图、1 张参考解答图');
  await panel.getByLabel('作答照片').setInputFiles(resolve('tests/fixtures/blank.png'));
  await panel.getByRole('button', { name: '开始 AI 批改', exact: true }).click();
  await expect(panel.getByText('AI 建议：部分对', { exact: true })).toBeVisible();
  const content = received!.messages[1].content;
  const images = content.filter(c => c.type === 'image_url').map(c => c.image_url!.url);
  expect(received!.model).toBe('gemini-3.8-flash');
  expect(images).toHaveLength(3);
  expect(images[0]).toMatch(/^data:image\/png;base64,/); expect(images[1]).toMatch(/^data:image\/png;base64,/); expect(images[2]).toMatch(/^data:image\/jpeg;base64,/);
  expect(content[1].text).toContain('题目给定的条件'); expect(content[3].text).toContain('标准答案的参考图'); expect(content[5].text).toContain('学生作答照片');
  expect(await page.evaluate(key => JSON.parse(localStorage.getItem(key) ?? '[]'), eventsKey)).toHaveLength(0);
  await expect(page.getByRole('button', { name: '记录', exact: true })).toBeDisabled();
  await panel.screenshot({ path: 'work/screenshots/grading-figure-context-mobile.png' });
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(376);
});

test('题图无法加载时停止模型调用，缺图不产生评分或学习记录', async ({ page, context }) => {
  await context.route('**/api/health', route => route.fulfill({ json: { ok: true, ai: true, sync: false, model: 'gemini-3.8-flash' } }));
  await page.addInitScript(key => localStorage.setItem(key, JSON.stringify({ aiEnabled: true, syncKey: 'test-sync-only' })), settingsKey);
  await context.route('**/figures/zt2026/q10-zp.png', route => route.fulfill({ status: 404, body: '测试缺图' }));
  let gradeCalls = 0;
  await context.route('**/api/grade', route => { gradeCalls++; return route.fulfill({ status: 502, json: { error: '不应发送本次缺图请求' } }); });
  await page.goto(base + '/#/p/zt2026-10');
  const panel = page.locator('.ai-panel');
  await panel.getByLabel('作答照片').setInputFiles(resolve('tests/fixtures/blank.png'));
  await panel.getByRole('button', { name: '开始 AI 批改', exact: true }).click();
  await expect(panel.getByRole('status')).toContainText('题图加载失败，本次未发送批改');
  await expect(panel.locator('details.external-grade')).toHaveAttribute('open', '');
  expect(gradeCalls).toBe(0);
  expect(await page.evaluate(key => JSON.parse(localStorage.getItem(key) ?? '[]'), eventsKey)).toHaveLength(0);
});

test('每日额度故障展开备用入口，回填后复核确认才保存和计数', async ({ page, context }) => {
  await context.route('**/api/health', route => route.fulfill({ json: { ok: true, ai: true, sync: false, model: 'gemini-3.8-flash' } }));
  await page.addInitScript(key => localStorage.setItem(key, JSON.stringify({ aiEnabled: true, syncKey: 'test-sync-only' })), settingsKey);
  let gradeCalls = 0;
  await context.route('**/api/grade', route => { gradeCalls++; return route.fulfill({ status: 502, json: { error: '模型项目的每日调用额度受限（429）', diagnostic: { kind: 'daily-quota', upstreamStatus: 429, retryAfterSeconds: 33 } } }); });
  await page.setViewportSize({ width: 375, height: 812 });
  await page.goto(base + '/#/p/tk-key-1-2');
  const panel = page.locator('.ai-panel');
  await panel.getByLabel('作答照片').setInputFiles(resolve('tests/fixtures/blank.png'));
  await panel.getByRole('button', { name: '开始 AI 批改', exact: true }).click();
  await expect(panel.getByRole('status')).toContainText('每日调用额度受限');
  await expect(panel.getByRole('link', { name: '查看 Gemini 调用用量' })).toHaveAttribute('href', 'https://aistudio.google.com/usage');
  await expect(panel).toContainText('每日额度需以 AI Studio 显示的重置时间');
  await expect(panel).not.toContainText('至少等待 33 秒');
  await expect(panel.locator('details.external-grade')).toHaveAttribute('open', '');
  expect(gradeCalls).toBe(1);
  expect(await page.evaluate(key => JSON.parse(localStorage.getItem(key) ?? '[]'), eventsKey)).toHaveLength(0);
  await panel.screenshot({ path: 'work/screenshots/grading-quota-fallback-mobile.png' });
  await panel.getByLabel('批改结果 JSON').fill(JSON.stringify({ ...result, problemId: 'tk-key-1-2' }));
  await panel.getByRole('button', { name: '读取批改结果' }).click();
  await panel.getByLabel('转写复核').selectOption('checked');
  await page.locator('label.tag').filter({ hasText: '计算失误' }).click();
  await page.locator('label.tag').filter({ hasText: '公式记错' }).click();
  await page.getByRole('button', { name: '记录', exact: true }).click();
  const saved = await page.evaluate(key => JSON.parse(localStorage.getItem(key) ?? '[]'), eventsKey);
  expect(saved).toHaveLength(1); expect(saved[0]).toMatchObject({ grade: 1, tags: ['公式记错'], recognition: { status: 'checked' }, ai: { tags: ['计算失误'], model: 'Gemini（手动导入）' } });
  expect(JSON.stringify(saved)).not.toContain('diagnostic'); expect(JSON.stringify(saved)).not.toContain('data:image');
  await page.goto(base + '/#/settings');
  const audit = page.locator('.grading-audit');
  await expect(audit).toContainText('人工确认转写正确 1 条，调整错因 1 条');
  await expect(audit).toContainText('调整评分 0 条');
  await audit.screenshot({ path: 'work/screenshots/grading-confirmed-tags-mobile.png' });
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(376);
});
