import type { Card } from '../../types';

const c = (id: string, kps: string[], front: string, back: string): Card => ({ id, kps, front, back });

export const coreCards: Card[] = [
  // 第一章
  c('c1-period-ct', ['1.2'], String.raw`连续信号 $\cos\omega_1t+\cos\omega_2t$ 何时是周期信号？周期怎么求？`,
    String.raw`当 $\frac{T_1}{T_2}=\frac{\omega_2}{\omega_1}$ 为**有理数**时是周期信号，周期为 $T_1$、$T_2$ 的最小公倍数；比值为无理数时非周期。例：$\sin2\pi t+\cos3\pi t$，$T_1=1,T_2=\frac23$，$T=2$。`),
  c('c1-period-dt', ['1.2'], String.raw`离散序列 $\cos(\Omega_0n)$ 何时是周期序列？周期是多少？`,
    String.raw`$\frac{2\pi}{\Omega_0}=\frac{N}{m}$ 为有理数（既约）时周期为 $N$；为无理数时非周期（如 $\cos n$）。例：$\cos\frac{3\pi}{7}n$：$\frac{2\pi}{3\pi/7}=\frac{14}{3}$，$N=14$。多个序列相加取最小公倍数。`),
  c('c1-energy-power', ['1.2'], '能量信号与功率信号如何判断？',
    String.raw`$0<E=\int|f|^2dt<\infty$ 为能量信号（此时 $P=0$）；$P=\lim\limits_{T\to\infty}\frac{1}{2T}\int_{-T}^{T}|f|^2dt$ 有限非零为功率信号（$E=\infty$）。有限幅度且有限时宽的非零信号是能量信号；常见非零周期信号、$u(t)$ 是功率信号；$e^{t}u(t)$、$tu(t)$ 两者都不是。冲激的平方不按普通函数积分处理。`),
  c('c1-delta-sift', ['1.4'], String.raw`冲激函数的筛选（抽样）性质？`,
    String.raw`$f(t)\delta(t-t_0)=f(t_0)\delta(t-t_0)$；$\int_a^bf(t)\delta(t-t_0)dt=f(t_0)$（$a<t_0<b$），$t_0$ 不在积分区间内则为 $0$。`),
  c('c1-delta-scale', ['1.4'], String.raw`$\delta(at)$ 与 $\delta(at-b)$ 等于什么？`,
    String.raw`$\delta(at)=\frac{1}{|a|}\delta(t)$；$\delta(at-b)=\frac{1}{|a|}\delta\!\left(t-\frac ba\right)$。$\delta(t)$ 是偶函数：$\delta(-t)=\delta(t)$。例：$\int\delta(3-2t)dt=\frac12$。`),
  c('c1-delta-prime', ['1.4'], String.raw`冲激偶 $\delta'(t)$ 的主要性质？`,
    String.raw`$\int f(t)\delta'(t-t_0)dt=-f'(t_0)$；$f(t)\delta'(t)=f(0)\delta'(t)-f'(0)\delta(t)$；$\delta'(-t)=-\delta'(t)$（奇函数）；$\int_{-\infty}^{\infty}\delta'(t)dt=0$。`),
  c('c1-delta-conv', ['1.4', '2.4'], String.raw`$\delta(t)$、$u(t)$ 与卷积的关系？`,
    String.raw`$\delta(t)=\frac{du(t)}{dt}$，$u(t)=\int_{-\infty}^t\delta(\tau)d\tau$；$f(t)*\delta(t-t_0)=f(t-t_0)$；$f*\delta'=f'$；$f*u=\int_{-\infty}^tf(\tau)d\tau$。`),
  c('c1-transform-order', ['1.5'], String.raw`由 $f(t)$ 画 $f(at+b)$ 的步骤？`,
    String.raw`先平移：$f(t)\to f(t+b)$（$b>0$ 左移）；再尺度：$f(t+b)\to f(at+b)$（$|a|>1$ 压缩）；$a<0$ 时再反褶。也可写成 $f[a(t+\frac ba)]$：先尺度、反褶，再平移 $\frac ba$。每一步都只对 $t$ 本身操作。`),
  c('c1-even-odd', ['1.6'], '信号的奇偶分解公式？',
    String.raw`$f_e(t)=\frac{f(t)+f(-t)}{2}$，$f_o(t)=\frac{f(t)-f(-t)}{2}$。例：$u(t)$ 的偶分量为 $\frac12$，奇分量为 $\frac12\mathrm{sgn}(t)$。`),
  c('c1-linear', ['1.8'], '如何判断系统是否线性？常见的非线性形式？',
    String.raw`同时满足齐次性和可加性：$T[ax_1+bx_2]=ay_1+by_2$。判断输入输出算子的线性时通常取零初态；固定的非零初态会额外带来零输入响应。动态线性系统对初态和输入联合满足叠加。常见非线性：$x^2$、$|x|$、$\sin x$、$e^{x}$、加常数项 $x+1$、$x(t)x(t-1)$。$y'+\sin t\cdot y=x$ 仍是**线性**微分方程，系数可以含 $t$。`),
  c('c1-ti', ['1.8'], '如何判断系统是否时不变？常见的时变形式？',
    String.raw`比较 $T[x(t-t_0)]$ 与 $y(t-t_0)$ 是否相等。系数含 $t$：$t\,x(t)$、$x(t)u(t)$、$x(t)\sin t$；尺度变换 $x(2t)$；反褶 $x(-t)$；积分上限 $\int_{-\infty}^{5t}x\,d\tau$ 都是**时变**的。`),
  c('c1-causal', ['1.8'], '如何判断系统是否因果？',
    String.raw`任意时刻的输出只取决于该时刻及以前的输入。$x(t+1)$、$x(-t)$、$x(2t)$、$\int_{-\infty}^{5t}x\,d\tau$ 非因果；$x(t)\sin(t+1)$ 是因果的（"未来"只出现在系数里）。LTI 系统：因果 ⟺ $h(t)=0,\ t<0$。`),
  c('c1-stable', ['1.8'], '如何判断系统是否稳定（BIBO）？',
    String.raw`有界输入必产生有界输出。LTI 系统：稳定 ⟺ $\int_{-\infty}^{\infty}|h(t)|dt<\infty$（离散 $\sum|h(n)|<\infty$）。积分器 $y=\int x\,d\tau$（$h=u(t)$）、$y=t\,x(t)$ 不稳定；$e^{x(t)}$、$\sin x(t)$ 稳定。`),

  // 第二章
  c('c2-decomp', ['2.2', '2.1'], '全响应的三种分解方式？',
    String.raw`全响应 = 零输入响应 + 零状态响应 = 自由响应 + 强迫响应 = 暂态响应 + 稳态响应。零输入只由初始状态决定，零状态只由激励决定；自由响应的形式由特征根决定（包括零输入的全部和零状态的一部分）；强迫响应的形式由激励决定。`),
  c('c2-decomp-trick', ['2.2'], String.raw`已知同一初始状态下激励 $x$、$kx$ 的全响应 $y_1$、$y_2$，如何求 $y_{zi}$、$y_{zs}$？`,
    String.raw`$y_1=y_{zi}+y_{zs}$，$y_2=y_{zi}+k\,y_{zs}$，联立解出。$k=2$ 时 $y_{zs}=y_2-y_1$，$y_{zi}=2y_1-y_2$。激励延时 $t_0$：$y=y_{zi}(t)+y_{zs}(t-t_0)$；初始状态 $\times a$、激励 $\times b$：$y=a\,y_{zi}+b\,y_{zs}$。`),
  c('c2-h-g', ['2.3'], String.raw`冲激响应 $h(t)$ 与阶跃响应 $g(t)$ 的关系？`,
    String.raw`通常卷积型 LTI 系统在积分存在时有 $g(t)=\int_{-\infty}^th(\tau)d\tau$，$h(t)=\frac{dg(t)}{dt}$；$s$ 域：$G(s)=\frac{H(s)}{s}$。求导后还需核对积分起点和常数基线；绝对可积核的阶跃响应在远负时间趋于0。离散：$g(n)=\sum_{k\le n}h(k)$，$h(n)=g(n)-g(n-1)$。`),
  c('c2-0minus', ['2.1'], String.raw`什么时候 $y(0^+)\neq y(0^-)$？如何处理？`,
    String.raw`微分方程右端含 $\delta(t)$ 或其导数时，$y$ 的高阶导数在 $0$ 时刻出现冲激，状态发生跳变。时域用冲激函数匹配法求 $0^+$ 值；$s$ 域法直接代入 $0^-$ 条件，跳变会自动包含在结果中。`),
  c('c2-conv-props', ['2.4'], '卷积积分的主要性质？',
    String.raw`交换律、结合律、分配律；微积分性质 $f_1*f_2=f_1'*f_2^{(-1)}$；时移 $f_1(t-t_1)*f_2(t-t_2)=y(t-t_1-t_2)$；起点 = 两起点之和，终点 = 两终点之和，时宽 = 两时宽之和。`),
  c('c2-rect-conv', ['2.4'], '两个矩形脉冲卷积的结果形状？',
    String.raw`宽 $T_1\ge T_2$、高 $A$、$B$ 的两矩形卷积为**梯形**：起点为两起点之和，终点为两终点之和，平顶宽 $T_1-T_2$，平顶高 $AB\,T_2$。等宽时为**三角形**。例：$[u(t)-u(t-1)]*[u(t-2)-u(t-3)]$ 为 $2\sim4$ 上峰值 $1$ 的三角形。`),
  c('c2-conv-table', ['2.4'], '常用卷积结果？',
    String.raw`$u*u=tu(t)$；$e^{-at}u(t)*u(t)=\frac1a(1-e^{-at})u(t)$；$e^{-at}u*e^{-bt}u=\frac{e^{-at}-e^{-bt}}{b-a}u(t)$（$a\ne b$）；$e^{-at}u*e^{-at}u=te^{-at}u(t)$。`),

  // 第三章
  c('c3-ft-table', ['3.3'], '常用傅里叶变换对（非周期）？',
    String.raw`取 $a>0$：$e^{-at}u(t)\leftrightarrow\frac{1}{a+j\omega}$；$e^{-a|t|}\leftrightarrow\frac{2a}{a^2+\omega^2}$；$\delta(t)\leftrightarrow1$；$1\leftrightarrow2\pi\delta(\omega)$；$u(t)\leftrightarrow\pi\delta(\omega)+\frac{1}{j\omega}$；$\mathrm{sgn}(t)\leftrightarrow\frac{2}{j\omega}$；$te^{-at}u(t)\leftrightarrow\frac{1}{(a+j\omega)^2}$。常量、阶跃和符号函数采用广义 FT，其中 $1/(j\omega)$ 按主值理解。`),
  c('c3-gate-sa', ['3.3', '1.3'], String.raw`门函数与 $\mathrm{Sa}$ 函数的变换对？`,
    String.raw`$G_\tau(t)$（宽 $\tau$、高 $1$、以原点为中心）$\leftrightarrow\tau\,\mathrm{Sa}\!\left(\frac{\omega\tau}{2}\right)$；对偶：$\mathrm{Sa}(\omega_ct)\leftrightarrow\frac{\pi}{\omega_c}G_{2\omega_c}(\omega)$，$\frac{\sin\omega_ct}{\pi t}\leftrightarrow G_{2\omega_c}(\omega)$。例：$u(t+2)-u(t-2)\leftrightarrow4\,\mathrm{Sa}(2\omega)$。`),
  c('c3-periodic-ft', ['3.5'], String.raw`$\cos\omega_0t$、$\sin\omega_0t$、$e^{j\omega_0t}$、周期冲激串的傅里叶变换？`,
    String.raw`$\cos\omega_0t\leftrightarrow\pi[\delta(\omega+\omega_0)+\delta(\omega-\omega_0)]$；$\sin\omega_0t\leftrightarrow j\pi[\delta(\omega+\omega_0)-\delta(\omega-\omega_0)]$；$e^{j\omega_0t}\leftrightarrow2\pi\delta(\omega-\omega_0)$；$\delta_T(t)\leftrightarrow\omega_0\sum\delta(\omega-n\omega_0)$，$\omega_0=\frac{2\pi}{T}$。一般周期信号：$f_T(t)\leftrightarrow2\pi\sum F_n\delta(\omega-n\omega_0)$。`),
  c('c3-scale-shift', ['3.4'], '傅里叶变换的尺度与时移性质？',
    String.raw`$f(at)\leftrightarrow\frac{1}{|a|}F\!\left(j\frac{\omega}{a}\right)$；$f(t-t_0)\leftrightarrow F(j\omega)e^{-j\omega t_0}$；合并：$f(at-b)\leftrightarrow\frac{1}{|a|}F\!\left(j\frac{\omega}{a}\right)e^{-j\omega b/a}$。例：$f(2t-9)\leftrightarrow\frac12F(j\frac{\omega}{2})e^{-j\frac92\omega}$。`),
  c('c3-freq-shift', ['3.4', '3.6'], '频移与调制性质？',
    String.raw`$f(t)e^{j\omega_0t}\leftrightarrow F(j(\omega-\omega_0))$；$f(t)\cos\omega_0t\leftrightarrow\frac12[F(j(\omega+\omega_0))+F(j(\omega-\omega_0))]$；$f(t)\sin\omega_0t\leftrightarrow\frac{j}{2}[F(j(\omega+\omega_0))-F(j(\omega-\omega_0))]$。`),
  c('c3-duality', ['3.4'], '对偶性质及典型应用？',
    String.raw`$f(t)\leftrightarrow F(j\omega)\Rightarrow F(jt)\leftrightarrow2\pi f(-\omega)$。应用：$\frac{1}{a+jt}\leftrightarrow2\pi e^{a\omega}u(-\omega)$；$\frac{1}{a^2+t^2}\leftrightarrow\frac{\pi}{a}e^{-a|\omega|}$；$\frac1t\leftrightarrow-j\pi\,\mathrm{sgn}(\omega)$；$\mathrm{Sa}(\omega_ct)\leftrightarrow\frac{\pi}{\omega_c}G_{2\omega_c}(\omega)$。`),
  c('c3-diff-int', ['3.4'], '傅里叶变换的时域/频域微分和积分性质？',
    String.raw`$f'(t)\leftrightarrow j\omega F(j\omega)$；$t\,f(t)\leftrightarrow j\frac{dF(j\omega)}{d\omega}$；$\int_{-\infty}^tf(\tau)d\tau\leftrightarrow\frac{F(j\omega)}{j\omega}+\pi F(0)\delta(\omega)$。例：$t\frac{dx}{dt}\leftrightarrow j\frac{d}{d\omega}[j\omega X]=-X-\omega X'$。`),
  c('c3-conv-thm', ['3.4'], '时域卷积与频域卷积定理？',
    String.raw`$f_1*f_2\leftrightarrow F_1(j\omega)F_2(j\omega)$；$f_1f_2\leftrightarrow\frac{1}{2\pi}F_1(j\omega)*F_2(j\omega)$。相乘后的最高频率不超过两带宽之和（$\mathrm{Sa}^2(\omega_ct)$ 为 $2\omega_c$）；卷积后的频谱支撑为两支撑的交集，最高频率不超过较小带宽，不一定达到此上界。`),
  c('c3-parseval', ['3.4'], String.raw`帕塞瓦尔定理与 $F(0)$、$f(0)$ 公式？`,
    String.raw`$\int|f(t)|^2dt=\frac{1}{2\pi}\int|F(j\omega)|^2d\omega$；$F(0)=\int f(t)dt$。满足反演条件时，对称频域积分在连续点给 $2\pi f(t)$，在跳点给 $2\pi[f(t^-)+f(t^+)]/2$；必要时须注明 Cauchy 主值，两端分别积分未必收敛。单点赋值不改变 F。例：$\int\sin t/t\,dt=\pi$；从0跳到2的原点，对称积分为2π。`),
  c('c3-fs', ['3.2'], '周期信号傅里叶级数（复指数形式）及频谱特点？',
    String.raw`$f(t)=\sum F_ne^{jn\omega_0t}$，$F_n=\frac1T\int_Tf(t)e^{-jn\omega_0t}dt$；三角形式 $\frac{a_0}{2}+\sum(a_n\cos n\omega_0t+b_n\sin n\omega_0t)$，$|F_n|=\frac{A_n}{2}$。周期信号有谐波线谱；通常可积周期信号的 $F_n\to0$，广义周期冲激串的系数却为常数。通常可积非周期信号有连续谱；不可公度正弦和等非周期信号仍可有广义线谱。频谱分为幅度谱、相位谱。`),
  c('c3-fs-sym', ['3.2'], '信号对称性与傅里叶级数系数的关系？',
    String.raw`偶函数：只含直流和余弦项（$b_n=0$）；奇函数：只含正弦项（$a_0=a_n=0$）；奇谐函数 $f(t\pm\frac T2)=-f(t)$：只含奇次谐波；偶谐函数：只含偶次谐波。`),
  c('c3-sine-steady', ['3.7'], '稳定 LTI 系统的正弦稳态响应公式？',
    String.raw`$A\cos(\omega_0t+\theta)\to A|H(j\omega_0)|\cos(\omega_0t+\theta+\varphi(\omega_0))$。例：$H(s)=\frac{1}{s+3}$，$4\sin(3t-5)\to\frac{2\sqrt2}{3}\sin(3t-5-\frac{\pi}{4})$（别漏乘输入幅度）。`),
  c('c3-distortionless', ['3.8'], '无失真传输的条件？',
    String.raw`时域：$y(t)=Kx(t-t_0)$，$h(t)=K\delta(t-t_0)$；频域：$H(j\omega)=Ke^{-j\omega t_0}$。当 $K>0$ 时，幅频特性为常数 $K$，相位 $\varphi(\omega)=-\omega t_0$；负 $K$ 还带来整体反相。只针对给定带限输入时，这些条件须在其频谱所在范围成立。`),
  c('c3-ideal-lpf', ['3.9'], '理想低通滤波器的频域、时域特性？',
    String.raw`$H(j\omega)=e^{-j\omega t_0}$（$|\omega|<\omega_c$），否则为 $0$；$h(t)=\frac{\omega_c}{\pi}\mathrm{Sa}[\omega_c(t-t_0)]$，$t<0$ 时不为零，**非因果、物理不可实现**。阶跃响应上升时间与带宽成反比，有吉布斯现象（约 9% 的过冲）。`),
  c('c3-modulation', ['3.6'], '调制与同步解调的原理？',
    String.raw`调制：$f(t)\cos\omega_0t$ 把频谱搬移到 $\pm\omega_0$，幅度减半。同步解调：再乘 $\cos\omega_0t$ 得 $\frac12f(t)+\frac12f(t)\cos2\omega_0t$，经低通（$\omega_m<\omega_c<2\omega_0-\omega_m$）滤除高频，放大 2 倍恢复 $f(t)$。`),
  c('c3-time-band', ['3.3', '3.4'], '信号的时宽与带宽之间是什么关系？',
    String.raw`**反比**关系：时域压缩，频域展宽（尺度性质 $f(at)\leftrightarrow\frac{1}{|a|}F(j\frac{\omega}{a})$）。矩形脉冲宽度 $\tau$ 越窄，Sa主瓣越宽：两侧首零点间全宽 $4\pi/\tau$ rad/s，单边首零点为 $2\pi/\tau$ rad/s或 $1/\tau$ Hz。矩形并非严格带限；这些是主瓣/首零点口径，不是有限的完整频谱支撑。`),

  // 第四章
  c('c4-lt-table', ['4.1'], '常用单边拉氏变换对？',
    String.raw`$\delta\leftrightarrow1$；$u\leftrightarrow\frac1s$；$e^{-at}u\leftrightarrow\frac{1}{s+a}$；$t^nu\leftrightarrow\frac{n!}{s^{n+1}}$；$te^{-at}u\leftrightarrow\frac{1}{(s+a)^2}$；$\sin\omega_0t\,u\leftrightarrow\frac{\omega_0}{s^2+\omega_0^2}$；$\cos\omega_0t\,u\leftrightarrow\frac{s}{s^2+\omega_0^2}$；$e^{-at}\cos\omega_0t\,u\leftrightarrow\frac{s+a}{(s+a)^2+\omega_0^2}$。`),
  c('c4-roc', ['4.1'], '双边拉氏变换的收敛域规律？',
    String.raw`右边信号：$\mathrm{Re}\{s\}>\sigma_0$（最右侧极点的右边）；左边信号：$\mathrm{Re}\{s\}<\sigma_0$；双边信号：带状区域；有限时宽信号：整个 $s$ 平面。ROC 内不含极点。例：$e^{-3t}u(t)-e^{-2t}u(-t)$ 的 ROC 为 $-3<\mathrm{Re}\{s\}<-2$。`),
  c('c4-shift', ['4.2'], '拉氏变换的时移、s 域平移、尺度性质？',
    String.raw`$f(t-t_0)u(t-t_0)\leftrightarrow F(s)e^{-st_0}$（注意 $u$ 也要平移）；$f(t)e^{-at}\leftrightarrow F(s+a)$；$f(at)\leftrightarrow\frac1aF(\frac sa)$（$a>0$）。例：$u(t)-u(t-1)\leftrightarrow\frac{1-e^{-s}}{s}$。`),
  c('c4-diff', ['4.2', '4.5'], '拉氏变换的微分、积分性质？',
    String.raw`$f'(t)\leftrightarrow sF(s)-f(0^-)$；$f''(t)\leftrightarrow s^2F(s)-sf(0^-)-f'(0^-)$；$\int_{0^-}^tf(\tau)d\tau\leftrightarrow\frac{F(s)}{s}$。`),
  c('c4-init-final', ['4.2'], '拉氏变换的初值定理和终值定理及使用条件？',
    String.raw`初值：$f(0^+)=\lim\limits_{s\to\infty}sF(s)$，要求信号不含原点冲激且初值存在；假分式先分离多项式对应的冲激项。终值：$f(\infty)=\lim\limits_{s\to0}sF(s)$。有理因果信号须使约分后的 $sF(s)$ 极点严格位于左半平面；等价地，$F(s)$ 除原点最多一个单极点外，其余极点均在左半平面。`),
  c('c4-pf', ['4.3'], '部分分式展开的系数求法？',
    String.raw`单极点 $K_i=(s-p_i)F(s)|_{s=p_i}$；二重极点 $K_{11}=(s-p)^2F|_{s=p}$，$K_{12}=\frac{d}{ds}[(s-p)^2F]|_{s=p}$；共轭复极点配方成 $(s+\alpha)^2+\beta^2$，用 $e^{-\alpha t}\cos\beta t$、$e^{-\alpha t}\sin\beta t$；假分式先长除，得到 $\delta$、$\delta'$ 项。`),
  c('c4-ilt-exp', ['4.3'], String.raw`象函数含 $e^{-st_0}$ 时如何求逆变换？`,
    String.raw`先对不含指数的部分 $F_1(s)$ 求逆变换 $f_1(t)$，再整体延时：$F_1(s)e^{-st_0}\leftrightarrow f_1(t-t_0)u(t-t_0)$。例：$\frac{s^2e^{-s}}{s^2+2s+2}$ 先长除 $\frac{s^2}{s^2+2s+2}=1-\frac{2s+2}{(s+1)^2+1}$，再延时 1。`),
  c('c4-truncated', ['4.1', '4.2'], String.raw`截断信号 $f(t)[u(t)-u(t-T)]$ 的拉氏变换怎么求？`,
    String.raw`方法一：直接积分 $\int_0^Tf(t)e^{-st}dt$。方法二：$f(t)u(t-T)=f[(t-T)+T]u(t-T)$，把 $f(t+T)$ 记为 $g(t)$，用时移性质。例：$e^{-at}[u(t)-u(t-T)]\leftrightarrow\frac{1-e^{-(s+a)T}}{s+a}$，逆变换为 $e^{-at}[u(t)-u(t-T)]$。`),
  c('c4-ft-exist', ['4.4'], String.raw`如何由 $H(s)$ 得到频率响应 $H(j\omega)$？何时不存在？`,
    String.raw`因果系统极点全在左半平面（ROC 含 $j\omega$ 轴）：$H(j\omega)=H(s)|_{s=j\omega}$。有右半平面极点：傅里叶变换不存在。$j\omega$ 轴上有单极点（如 $\frac1s$）：傅里叶变换存在，但含冲激项，不能直接代 $s=j\omega$。`),
  c('c4-zp-K', ['4.6'], String.raw`由零极点图求 $H(s)$ 时，增益 $K$ 怎么确定？`,
    String.raw`$H(s)=K\frac{\prod(s-z_i)}{\prod(s-p_j)}$。常见附加条件：$h(0^+)=\lim\limits_{s\to\infty}sH(s)$；$H(0)$ 的值（直流增益）；阶跃响应终值 $g(\infty)=H(0)$。`),
  c('c4-block', ['4.6', '1.7'], '框图的串联、并联、反馈怎样化简？',
    String.raw`串联：$H_1H_2$；并联：$H_1+H_2$；负反馈（前向 $G$、反馈 $H$）：$\frac{G}{1+GH}$；正反馈：$\frac{G}{1-GH}$。例：前向 $\frac{1}{(s+2)(s+4)}$，负反馈 $\frac Ks$：$H=\frac{s}{s^3+6s^2+8s+K}$。`),
  c('c4-hs-ode', ['4.6'], String.raw`$H(s)$ 与微分方程如何互相转换？`,
    String.raw`$H(s)=\frac{b_ms^m+\cdots+b_0}{s^n+a_{n-1}s^{n-1}+\cdots+a_0}\iff y^{(n)}+a_{n-1}y^{(n-1)}+\cdots+a_0y=b_mx^{(m)}+\cdots+b_0x$。例：$\frac{s+5}{s^2+5s+6}\iff y''+5y'+6y=x'+5x$。`),
  c('c4-direct-form', ['4.6', '1.7'], '如何由 H(s) 画直接型模拟框图？',
    String.raw`分子分母同除以 $s^n$，化成 $s^{-1}$ 多项式；$n$ 个积分器串联，分母系数取负作反馈送回输入加法器，分子系数作前馈送入输出加法器。`),
  c('c4-stable', ['4.7'], '连续因果 LTI 系统稳定的极点条件？',
    String.raw`极点全部在 $s$ 左半平面 ⟺ 稳定；$j\omega$ 轴上有单极点：临界稳定（按 BIBO 定义不稳定）；右半平面有极点或 $j\omega$ 轴上有重极点：不稳定。`),
  c('c4-routh', ['4.7'], '劳斯判据要点？三阶系统的稳定条件？',
    String.raw`必要条件：特征多项式各系数同号且不缺项。劳斯表第一列全为正 ⟺ 稳定，第一列变号次数等于右半平面根数。三阶 $s^3+a_2s^2+a_1s+a_0$：稳定 ⟺ $a_2,a_1,a_0>0$ 且 $a_2a_1>a_0$。例：$s^3+6s^2+8s+K$ → $0<K<48$。`),
  c('c4-pole-time', ['4.6'], '极点位置对时域响应的影响？',
    String.raw`左半平面实极点 → 衰减指数，离虚轴越远衰减越快；共轭复极点 → 振荡，实部决定衰减，虚部决定振荡频率；右半平面 → 增长；$j\omega$ 轴单极点 → 等幅（$s=0$ 为阶跃，$\pm j\omega_0$ 为等幅正弦）。零点只影响各分量的幅度和相位。`),
  c('c4-s-solve', ['4.5'], 's 域求全响应的步骤？',
    String.raw`微分方程两边取单边拉氏变换，代入 $y(0^-)$、$y'(0^-)$；整理成 $Y(s)=Y_{zi}(s)+Y_{zs}(s)$，其中 $Y_{zs}=H(s)X(s)$，$Y_{zi}$ 的分子由初始状态决定；分别部分分式求逆变换。`),

  // 第五章
  c('c5-sampling', ['5.2'], '时域抽样定理？奈奎斯特频率与间隔？',
    String.raw`最高频率为 $f_m$ 的带限信号通常取 $f_s>2f_m$，教材将临界奈奎斯特率写为 $2f_m$。在恰好等号时，边界若有谱线仍可能混叠，例如 $\sin(2\pi f_mt)$ 以 $2f_m$ 采样全为零。奈奎斯特间隔 $T_N=\frac{1}{2f_m}$。例：2 kHz → $250\ \mu s$；$f(3t)$ 的 6 kHz 带宽 → 12 kHz 临界率。冲激抽样使复制谱乘 $1/T_s$；若抽样前还有非零的 $H_1$，恢复原输入的滤波器在输入带内需 $H_2=T_s/H_1$，带外设计只需避免复制谱干扰。`),
  c('c5-band-ops', ['5.2', '3.4'], '信号运算后最高频率如何变化？',
    String.raw`最高频率的通常上界：相加取较大者，相乘取两者之和，平方取 $2\omega_m$，卷积取较小者；实际支撑须考虑抵消和谱带交集。$f(at)$ 的最高频率为 $|a|\omega_m$；时移不改变支撑，微分可能消去直流。$\mathrm{Sa}(\omega_ct)$（$\omega_c>0$）最高角频率为 $\omega_c$，平方为 $2\omega_c$。例：$\mathrm{Sa}(60t)+\mathrm{Sa}^2(60t)$：$\omega_m=120$，临界采样率 $120/\pi$ Hz。`),
  c('c5-bandpass', ['5.2'], '频谱为 $f_L\sim f_H$ 的带通信号，抽样周期最大不得超过多少（真题口径）？',
    String.raw`按低通抽样定理：$f_s\ge2f_H$，$T_{\max}=\frac{1}{2f_H}$。例：频谱 5 kHz~10 kHz → $T_{\max}=50\ \mu s$。`),

  // 第六章
  c('c6-seq', ['6.1'], '常用序列及相互关系？',
    String.raw`$\delta(n)=u(n)-u(n-1)$；$u(n)=\sum_{k\le n}\delta(k)=\sum_{k=0}^{\infty}\delta(n-k)$；矩形序列 $R_N(n)=u(n)-u(n-N)$；任意序列 $x(n)=\sum x(k)\delta(n-k)$。`),
  c('c6-conv-sum', ['6.2'], '卷积和的计算方法与结果长度？',
    String.raw`$y(n)=\sum_kx(k)h(n-k)$。有限长序列用**不进位乘法**对位相乘相加；起点 = 两起点之和，长度 $N_1+N_2-1$；$x(n)*\delta(n-n_0)=x(n-n_0)$；$x*u=\sum_{k\le n}x(k)$；校验 $\sum y=\sum x\cdot\sum h$。`),
  c('c6-lsi', ['6.3'], '离散系统的因果、稳定条件和常见时变形式？',
    String.raw`LSI 系统：因果 ⟺ $h(n)=0,\ n<0$；稳定 ⟺ $\sum|h(n)|<\infty$。$y(n)=n\,x(n)$、$x(-n)$、$x(2n)$ 时变；$y(n)=x(n)x(n-1)$、$e^{x(n)}$ 非线性。`),
  c('c6-classical', ['6.4'], '差分方程经典解法的要点？',
    String.raw`特征方程 → 齐次解 $C\lambda^n$（重根 $Cn\lambda^n$）；特解按激励设：常数 → $P$，$a^n$ → $Pa^n$（$a$ 是特征根时乘 $n$）。零输入响应用 $y(-1),y(-2)$ 定系数；零状态响应要令初始状态为 $0$，先递推出 $y(0),y(1)$ 再定系数。`),
  c('c6-diagram', ['6.4', '7.7'], '离散框图如何写差分方程？',
    String.raw`设第一个加法器的输出为 $w(n)$：$w(n)=x(n)+\sum a_kw(n-k)$，$y(n)=\sum b_kw(n-k)$。$z$ 域消去 $W(z)$ 得 $H(z)=\frac{\sum b_kz^{-k}}{1-\sum a_kz^{-k}}$，再交叉相乘写差分方程。注意反馈支路的正负号。`),

  // 第七章
  c('c7-zt-table', ['7.1'], '常用 z 变换对（含收敛域）？',
    String.raw`$\delta(n)\leftrightarrow1$（全平面）；$u(n)\leftrightarrow\frac{z}{z-1}$，$|z|>1$；$a^nu(n)\leftrightarrow\frac{z}{z-a}$，$|z|>|a|$；$-a^nu(-n-1)\leftrightarrow\frac{z}{z-a}$，$|z|<|a|$；$na^nu(n)\leftrightarrow\frac{az}{(z-a)^2}$；$nu(n)\leftrightarrow\frac{z}{(z-1)^2}$。`),
  c('c7-roc', ['7.1'], 'z 变换收敛域与序列类型的对应？',
    String.raw`有限长序列：$0<|z|<\infty$（可能含 $0$ 或 $\infty$）；右边序列：$|z|>R$（圆外）；左边序列：$|z|<R$（圆内）；双边序列：圆环。ROC 内无极点，以极点为边界。`),
  c('c7-causal-stable', ['7.7'], '离散系统因果、稳定的 ROC 条件？',
    String.raw`因果 ⟺ ROC 为 $|z|>R$ 且包含 $\infty$；稳定 ⟺ ROC 包含单位圆 $|z|=1$；因果稳定 ⟺ 极点全在单位圆内。`),
  c('c7-shift', ['7.3', '7.6'], 'z 变换的移位性质（双边与单边）？',
    String.raw`双边：$x(n-m)\leftrightarrow z^{-m}X(z)$。单边：$x(n-1)u(n)\leftrightarrow z^{-1}X(z)+x(-1)$；$x(n-2)u(n)\leftrightarrow z^{-2}X(z)+z^{-1}x(-1)+x(-2)$；$x(n+1)u(n)\leftrightarrow zX(z)-zx(0)$。`),
  c('c7-init-final', ['7.3'], 'z 变换的初值定理和终值定理及条件？',
    String.raw`初值（因果序列）：$x(0)=\lim\limits_{z\to\infty}X(z)$。终值：$x(\infty)=\lim\limits_{z\to1}(z-1)X(z)$，要求极点都在单位圆内（$z=1$ 处最多一阶极点）。用前必须检查条件。`),
  c('c7-props', ['7.3'], 'z 变换的其他常用性质？',
    String.raw`$a^nx(n)\leftrightarrow X(\frac za)$；$nx(n)\leftrightarrow-z\frac{dX(z)}{dz}$；$x_1*x_2\leftrightarrow X_1X_2$（ROC 至少为交集）；$x(-n)\leftrightarrow X(\frac1z)$。`),
  c('c7-pf', ['7.2'], '部分分式法求 z 反变换的步骤？',
    String.raw`先对 $\frac{X(z)}{z}$ 展开，再乘回 $z$ 得 $\sum K_i\frac{z}{z-p_i}$；按 ROC 判断每一项：极点在 ROC 内侧 → $p_i^nu(n)$；极点在 ROC 外侧 → $-p_i^nu(-n-1)$。`),
  c('c7-roc-all', ['7.7', '7.1'], 'H(z) 有 N 个不同模值的极点，可能有几种 ROC？',
    String.raw`$N+1$ 种：最外侧圆外 → 因果；最内侧圆内 → 反因果；中间圆环 → 双边。其中包含单位圆的那一种对应稳定系统。`),
  c('c7-freq', ['7.7', '7.5'], '离散系统的频率响应怎么求？有什么特点？',
    String.raw`稳定系统：$H(e^{j\omega})=H(z)|_{z=e^{j\omega}}$，以 $2\pi$ 为周期；$|H(e^{j\omega})|$ 可由零点向量长度之积除以极点向量长度之积估计，$\omega=0$ 对应 $z=1$，$\omega=\pi$ 对应 $z=-1$。`),
  c('c7-spectra', ['7.5', '3.2'], '时域连续/离散、周期/非周期与频谱特性的对应？',
    String.raw`连续非周期 → 连续非周期谱；连续周期 → 离散非周期谱；离散非周期 → **连续周期**谱；离散周期 → 离散周期谱。口诀：时域离散 ⟺ 频域周期，时域周期 ⟺ 频域离散。`),
  c('c7-solve', ['7.6'], 'z 域解差分方程的步骤？',
    String.raw`两边取单边 $z$ 变换，用移位性质代入 $y(-1),y(-2)$；整理成 $Y(z)=Y_{zi}(z)+Y_{zs}(z)$，$Y_{zs}=H(z)X(z)$；分别对 $\frac{Y}{z}$ 部分分式求反变换。`),
  c('c7-sz', ['7.4'], 's 平面与 z 平面的映射关系？',
    String.raw`$z=e^{sT}$：$s$ 左半平面 ↔ 单位圆内；$j\omega$ 轴 ↔ 单位圆；右半平面 ↔ 单位圆外；$s=0$ ↔ $z=1$。`),
];
