"""从外校原题独立求解并核验33个精选作答单元，不读取网页答案。"""
from common import *

v = Symbol('v', real=True)
om = Symbol('omega', real=True)
T = Symbol('T', positive=True)

# 西安理工：分布定义、连续积分与离散定义。
phi = exp(-v*v)*(1+3*v)
eq('西安一1 (1-v)δ导数在测试函数上的作用', -diff((1-v)*phi, v).subs(v, 0), phi.subs(v, 0)-diff(phi, v).subs(v, 0))
eq('西安一2 单侧周期反例的右端', cos(pi*2), 1)
check('西安一2 负半轴截断不能周期延拓', 0 != cos(0))
A = integrate(v, (v, 0, t))
eq('西安一3 第一段卷积', A, t*t/2)
eq('西安一3 第二段卷积', integrate(v, (v, t-2, t)), 2*t-2)
eq('西安一3 δ导数延时后的斜坡段', diff(A, t).subs(t, t-2), t-2)
eq('西安一3 末段平台', diff(2*t-2, t), 2)
for k in [-2,0,1,3,4,5,9]:
    eq(f'西安一4 定义卷积 k={k}', sum(u(k-m) for m in range(5)), (k+1)*u(k)-(k-4)*u(k-5))
eq('西安一5 矩形谱直接反变换', integrate(exp(I*om*t), (om, -2*pi, 2*pi))/(2*pi), sin(2*pi*t)/(pi*t))
eq('西安一5 t0可去奇点', limit(sin(2*pi*t)/(pi*t), t, 0), 2)
eq('西安一7 延时余弦单边积分', integrate(cos(3*t-2)*exp(-s*t), (t, Rational(2,3), oo)), exp(-2*s/3)*s/(s*s+9))
eq('西安一9 从下标定义双边Z', sum(a*z**(-k) for k,a in {-1:2,0:1,2:-1}.items()), 2*z+1-z**-2)
eq('西安一10 未来输入区间确实产生非零输出', integrate(exp(2*(v-1)), (v, t, t+1)), (exp(2*t)-exp(2*t-2))/2)
check('西安二1 映射端点', [2-i for i in [-2,0,2]] == [4,2,0])
eq('西安二1 斜线反折表达式', (v+2).subs(v, 2-t), 4-t)
H = (s-1)/(s+2)
g = -Rational(1,2)+Rational(3,2)*exp(-2*t)
eq('西安三2 阶跃变换', lt(g), H/s)
eq('西安三2 普通导数', diff(g,t), -3*exp(-2*t))
eq('西安三2 跳变产生单位冲激', g.subs(t,0), 1)
eq('西安三4 三角恒等式', expand_trig(8*cos(t)*cos(5*t)**2), expand_trig(4*cos(t)+2*cos(11*t)+2*cos(9*t)))
eq('西安三5 从反馈消元', (1/s+4/s**3)/(1+3/s+2/s**2), (s*s+4)/(s*(s+1)*(s+2)))
eq('西安三5 反变换', lt(2-5*exp(-t)+4*exp(-2*t)), (s*s+4)/(s*(s+1)*(s+2)))
eq('西安三6 从输入输出Z相除', (2*z/(z-Rational(1,2))+2*z/(z-Rational(1,3)))/(z/(z-Rational(1,2))), (4*z-Rational(5,3))/(z-Rational(1,3)))
def xx(k): return Rational(1,2)**k*u(k)
def yy(k): return (2*Rational(1,2)**k+2*Rational(1,3)**k)*u(k)
recurrence('西安三6 输入输出递推含首拍', yy, [1,-Rational(1,3)], lambda k: 4*xx(k)-Rational(5,3)*xx(k-1))

# 沈航：图中4是冲激强度，不是波形高度。
def triangle(k): return max(0, 2-abs(k))
check('沈航一1 输出转折点', [triangle(k+1)-triangle(k-1) for k in [-3,-1,1,3]] == [0,2,-2,0])
eq('沈航一2 冲激面积随尺度除2', Integer(4)/2, 2)
check('沈航一2 普通波形边界连续和末端跳变', 0 == (-1+1) and (0+1)==1 and 0-1==-1)
eq('沈航一3 反变换指数', (2*v-4).subs(v, (4-t)/2), -t)
eq('沈航一3 积分含面积2', 2+integrate(exp(-t),(t,0,oo)), 3)
eq('沈航一4 频域冲激的反变换系数', Rational(1,2)/(2*pi), 1/(4*pi))
# 指数核衰减率为1，对所有实ω绝对可积，移除SymPy未化简的arg条件分支。
eq('沈航一4 延时傅里叶积分', integrate(exp(-t+2)*exp(-I*om*t),(t,2,oo), conds='none'), exp(-2*I*om)/(1+I*om))
h1 = {0:1,1:1,2:1}; h2={0:1,1:-1}
def conv(a,b,k): return sum(x*b.get(k-i,0) for i,x in a.items())
result = {k:conv(h1,h2,k)-h1.get(k,0)+conv(h1,h1,k) for k in range(7)}
check('沈航一5 逐支路卷积符号', [result[k] for k in range(7)] == [1,1,2,1,1,0,0])
eq('沈航一5 面积对应DC增益', sum(result.values()), 6)
eq('沈航一6 平方谱支撑卷积展宽', 2*100*pi/(2*pi)*2, 200)
def hs(k): return Rational(1,2)**(k-1)*u(k-1)
for k in range(9):
    eq(f'沈航一8 阶跃差分 n={k}', 2*(1-Rational(1,2)**k)*u(k)-2*(1-Rational(1,2)**(k-1))*u(k-1), hs(k))
    eq(f'沈航一8 从定义卷积 n={k}', sum(hs(m)*xx(k-m) for m in range(-2, k+3)), k*Rational(1,2)**(k-1)*u(k-1))
impedance = (s+1)/(s+3)
eq('沈航二2 零状态元件阻抗消元', impedance/(1/s+impedance)*2/(s+1), 2*s/(s*s+2*s+3))
check('沈航二2 全部极点实部负', roots(s*s+2*s+3,s)=={-1+I*sqrt(2),-1-I*sqrt(2)})
eq('沈航二3 模拟框图消元', (1/s+4/s**2)/(1+3/s+2/s**2), (s+4)/(s*s+3*s+2))
eq('沈航二3 正弦频响', ((s+4)/(s*s+3*s+2)).subs(s,I), (7-11*I)/10)
eq('沈航二3 正弦输出幅值', 2*Abs((7-11*I)/10), sqrt(170)/5)
zi = 6*exp(-t)-4*exp(-2*t); zs = 2-3*exp(-t)+exp(-2*t)
eq('沈航二3 零输入ODE', diff(zi,t,2)+3*diff(zi,t)+2*zi, 0)
eq('沈航二3 零输入初值', zi.subs(t,0), 2)
eq('沈航二3 零输入导数', diff(zi,t).subs(t,0), 2)
eq('沈航二3 零状态阶跃变换', lt(zs), (s+4)/(s*(s+1)*(s+2)))
eq('沈航二3 全响应导数跳变', diff(zi+zs,t).subs(t,0), 3)
eq('沈航二4 零极点因式分解', (2+1/z)/(1+3/z+2/z**2), z*(2*z+1)/((z+1)*(z+2)))
def hd(k): return (-(-1)**k+3*(-2)**k)*u(k)
recurrence('沈航二4 冲激首拍到尾部', hd, [1,3,2], lambda k:2*Integer(k==0)+Integer(k==1))

# 山西：保留未平移指数、多项式的广义函数项与0+初值。
eq('山西1 非零支撑内的卷积积分', integrate(6*exp(-2*v)*exp(-(t-v)),(v,1,t-2)), 6*(exp(-t-1)-exp(2-2*t)))
eq('山西1 支撑起点连续归零', (6*(exp(-t-1)-exp(2-2*t))).subs(t,3), 0)
F=(s**3+5*s*s+9*s+7)/((s+1)*(s+2))
eq('山西2 分离δ与δ导数项', F, s+2+2/(s+1)-1/(s+2))
eq('山西3 长除法和延时', (z-1)/(z*z*(z-2)), z**-2*(1+1/(z-2)))
zi=(1+4*t)*exp(-3*t); zs=t*t/9-t/27+t*exp(-3*t)/27
eq('山西4 零输入齐次ODE', diff(zi,t,2)+6*diff(zi,t)+9*zi, 0)
eq('山西4 零状态非齐次ODE', diff(zs,t,2)+6*diff(zs,t)+9*zs, t*t+t)
eq('山西4 零输入初值', zi.subs(t,0), 1)
eq('山西4 零输入导数初值', diff(zi,t).subs(t,0), 1)
eq('山西4 零状态初值', zs.subs(t,0), 0)
eq('山西4 零状态导数初值', diff(zs,t).subs(t,0), 0)
Y=8*exp(-2*t)-Rational(11,2)*exp(-3*t)-exp(-t)/2
eq('山西6 从频响还原系统函数', (-I*om)/(om**2-5*I*om-6), (s/((s+2)*(s+3))).subs(s,I*om))
eq('山西6 全响应ODE t正', diff(Y,t,2)+5*diff(Y,t)+6*Y, -exp(-t))
eq('山西6 0+初值', Y.subs(t,0), 2)
eq('山西6 0+导数', diff(Y,t).subs(t,0), 1)
eq('山西7 连续微分频响定义', diff(exp(I*om*t),t)/exp(I*om*t), I*om)
eq('山西7 离散微分频响模平方', expand_complex((1-exp(-I*om))*(1-exp(I*om))/T**2), 4*sin(om/2)**2/T**2)
eq('山西7 正半轴幅相表示', 2*I*exp(-I*om/2)*sin(om/2), 1-exp(-I*om))
eq('山西7 离散频响周期', (1-exp(-I*(om+2*pi)))/T, (1-exp(-I*om))/T)
eq('山西7 物理低频极限', limit((1-exp(-I*om*T))/(I*om*T),om,0), 1)
band=Symbol('omega_m',positive=True)
eq('山西8 压缩信号抽样频率Hz', 2*(2*band)/(2*pi), 2*band/pi)
eq('山西8 伸展信号抽样频率Hz', 2*(band/2)/(2*pi), band/(2*pi))
eq('山西8 抽样临界周期', 2*pi/(2*band), pi/band)
finish()
