"""2018 印刷卷：有限积分、复数幅相、LT/FT 性质与递推复核。"""
from common import *

eq('一1 冲激乘积系数',exp(-(t-2)).subs(t,3),exp(-1))
# 左边信号的双边积分，从负无穷到零，要求 s 在两极点左侧。
sl=Symbol('sl',real=True)
left=integrate(-(exp(-3*t)+exp(-t))*exp(-sl*t),(t,-oo,0),conds='none')
eq('一2 左边逆 LT',left,1/(sl+3)+1/(sl+1))
T=Symbol('T',nonnegative=True)
eq('一3 含阶跃延时',1-(1+exp(-s*T))/s,1-1/s-exp(-s*T)/s)
check('一5 稳定 ROC', max(-2,-3)==-2 and -2<0)
check('一6 高通输出',80*pi<100*pi<120*pi and 2*5==10)
eq('一7 由 H 得 ODE',(s+2)/(s**2+4*s+3),(s+2)/((s+1)*(s+3)))
H=(s**2+3*s+2)/(s**2+5*s+6)
eq('一8 含直通的 h',1+lt(-2*exp(-3*t)),H)
eq('一9 奈奎斯特',2*600*pi/(2*pi),600)
check('一10 卷积延时抵消',-1+1==0)
check('二1 低通输出',100*pi<120*pi<200*pi and 2*10==20)
eq('二2 矩形窗 FT',integrate(exp(-I*w*t),(t,-1,1)),2*sin(w)/w)
eq('二3 正确冲激积分', (2+t).subs(t,-1),Integer(1))
check('二4 卷积总延时',-1+2==1)
eq('二5 复指数调制',exp(-I*w*t)*exp(I*t),exp(-I*(w-1)*t))
eq('二6 有限阶跃窗 LT',integrate(exp(-s*t),(t,0,1)),(1-exp(-s))/s)
eq('二7 直流增益定 K',limit(3*(s+2)/((s+3)*(s+1)),s,0),2)
eq('二8 两边逆 LT 右项',lt(exp(-3*t)),1/(s+3))
eq('二9 原选项均不正确',lt(exp(-2*t)+t*exp(-t)),1/(s+2)+1/(s+1)**2)
check('二10 稳定因果极点',all(p<0 for p in [-1,-3]))

# 系统性质的时变见证：输入常数，乘 sin(2t) 后移位不保持。
eq('三1-1 线性系数', (2+3)*sin(2*t),2*sin(2*t)+3*sin(2*t))
check('三1-1 时变见证',sin(2*(t-1))!=sin(2*t))
check('三1-2 非线性见证',exp(1+1)!=exp(1)+exp(1))
T=Symbol('T',positive=True)
eq('三2 卷积第一段',integrate(t-tau,(tau,0,t)),t**2/2)
eq('三2 卷积第二段',integrate(t-tau,(tau,0,T)),T*t-T**2/2)
eq('三2 卷积第三段',integrate(t-tau,(tau,t-2*T,T)),-t**2/2+T*t+3*T**2/2)
F=Function('F')
eq('三3-1 t 乘尺度信号',I*diff(F(w/2)/2,w),I*Subs(Derivative(F(w),w),w,w/2)/4)
eq('三3-2 反褶后的时间加权', exp(-I*w)*(F(-w)-I*diff(F(-w),w))-exp(-I*w)*F(-w), I*exp(-I*w)*Subs(Derivative(F(w),w),w,-w))
eq('三3-3 t x导数',I*diff(I*w*F(w),w),-F(w)-w*diff(F(w),w))
eq('三4 延时前的普通部分',1+lt(-2*exp(-t)*cos(t)),s**2/(s**2+2*s+2))
eq('三5 sinc 抽样周期',pi/(4*pi),Rational(1,4))
k=Symbol('k',nonzero=True)
hn=lambda j:k**j*u(j)
recurrence('三6-1 一阶冲激响应',hn,[1,-k],lambda j:Integer(j==0))
yn=lambda j:Integer(4) if j==-1 else (2+Rational(1,2)**j if j>=0 else 0)
check('三6-2 含初态全响应',all(yn(j)-Rational(1,2)*yn(j-1)==1 for j in range(15)))
finish()
