"""2023 回忆卷；频率单位与不完整题面在网页保留说明。"""
from common import *

eq('一1 筛选权重',4*sin(pi/6),Integer(2))
b=Symbol('b',real=True)
f=Function('f')
eq('一2 积分后导数校验',diff(f(t+b),t),Subs(Derivative(f(t),t),t,t+b))
eq('一3 阶跃跳变不能遗漏',1+lt(-3*exp(-3*t)),s*lt(exp(-3*t)))
eq('一5 连续基本周期',2*pi/Integer(1),2*pi)
check('一5 离散非周期',pi.is_irrational)
eq('一6 指数 LT',lt(exp(-2*t)),1/(s+2))
eq('一7 无失真相位',exp(-I*w*b),cos(w*b)-I*sin(w*b))
eq('一8 余弦分解',(exp(I*b*t)+exp(-I*b*t))/2,cos(b*t))
eq('二1 先提尺度再时移',-2*(t-Rational(5,2)),5-2*t)
eq('二2 由输出反求输入',(1/((I*w+2)*(I*w+3)))/(1/(I*w+2)),1/(I*w+3))
check('二3 非可逆反例',0*1==0*2)
eq('二4 带宽并集的奈奎斯特 Hz',2*max(100,2*60)/(2*pi),120/pi)
check('二5 带宽交集',Interval(-10,10).intersect(Interval(-20,20))==Interval(-10,10))
check('二6 稳定因果 ROC 的虚轴',Interval.open(-2,oo).contains(0))
eq('二7 有限窗 LT',integrate(exp(-s*t),(t,0,1)),(1-exp(-s))/s)
eq('三1 反褶斜段',((t+1).subs(t,2-t)),3-t)
check('三1 区间反射',sorted([2-(-1),2-0])==[2,3] and sorted([2-0,2-1])==[1,2])
eq('三2 卷积第一段',integrate(exp(-(t-tau)),(tau,0,t)),1-exp(-t))
eq('三2 卷积第二段',integrate(exp(-(t-tau)),(tau,0,1)),(exp(1)-1)*exp(-t))
eq('三3 移位矩形谱逆变换',integrate(exp(I*w*(t-2)),(w,-2*pi,2*pi))/(2*pi),sin(2*pi*(t-2))/(pi*(t-2)))

# 三年共用的四道零极点综合题，避免把 h(0+) 与 H(0) 混用。
H=2*s/(s**2+2*s+Rational(7,4))
check('四1 复极点',roots(s**2+2*s+Rational(7,4),s)=={-1+I*sqrt(3)/2,-1-I*sqrt(3)/2})
eq('四1 初值确定增益',limit(s*H,s,oo),Integer(2))
eq('四2 频率响应',H.subs(s,I*w),2*I*w/(Rational(7,4)-w**2+2*I*w))
ht=exp(-t)*(2*cos(sqrt(3)*t/2)-4*sqrt(3)/3*sin(sqrt(3)*t/2))
eq('四3 修正正弦余弦项',lt(ht),H)
eq('四3 时域初值',limit(ht,t,0),Integer(2))
Hj=H.subs(s,I*sqrt(3)/2)
eq('四4 正弦幅度',Abs(Hj),sqrt(3)/2)
eq('四4 正弦相角',arg(Hj),pi/6)
finish()
