import type { KnowledgePoint } from '../types';

// 依据"2027 院校重点圈画·中北大学 808"表录入，星级为该表给出的重要程度
export const knowledge: KnowledgePoint[] = [
  { id: '1.1', chapter: 1, title: '信息、信号和系统', scope: '基本概念，了解即可', stars: 1 },
  { id: '1.2', chapter: 1, title: '信号的分类与描述', scope: '连续/离散、实/复、周期与非周期、能量/功率信号特性', stars: 5 },
  { id: '1.3', chapter: 1, title: '常用典型信号', scope: '指数、正弦、矩形脉冲、Sa/抽样信号', stars: 4 },
  { id: '1.4', chapter: 1, title: '奇异信号及其特性', scope: '阶跃、冲激、冲激偶的基本公式及性质', stars: 5 },
  { id: '1.5', chapter: 1, title: '信号的基本运算及波形变换', scope: '时移、反褶、尺度、微分、积分、对称性质，作图', stars: 5 },
  { id: '1.6', chapter: 1, title: '信号的分解', scope: '直流/交流、奇偶、实虚分解', stars: 4 },
  { id: '1.7', chapter: 1, title: '系统模型、特性及分类', scope: '系统框图绘图，可逆与不可逆系统', stars: 4 },
  { id: '1.8', chapter: 1, title: '线性时不变系统性质', scope: '线性、时不变、因果、稳定判定条件', stars: 5 },
  { id: '1.9', chapter: 1, title: 'LTI 系统分析方法概述', scope: '了解即可', stars: 1 },
  { id: '2.1', chapter: 2, title: '经典时域解法', scope: '微分方程建立与求解、0−到0+、冲激函数匹配法、自由/强迫响应、暂态/稳态响应', stars: 5 },
  { id: '2.2', chapter: 2, title: '零输入响应和零状态响应', scope: '零输入响应、零状态响应的求解', stars: 5 },
  { id: '2.3', chapter: 2, title: '冲激响应和阶跃响应', scope: 'h(t)、g(t) 的定义及两者关系', stars: 5 },
  { id: '2.4', chapter: 2, title: '卷积积分', scope: '定义、图解法、性质，卷积求零状态响应', stars: 5 },
  { id: '2.5', chapter: 2, title: '相关', scope: '相关函数定义、与卷积关系，了解即可', stars: 1 },
  { id: '3.1', chapter: 3, title: '信号的正交分解', scope: '正交性、展开与基本表示，无需了解', stars: 1 },
  { id: '3.2', chapter: 3, title: '周期信号傅里叶级数', scope: '三角/复指数形式，频谱图，帕塞瓦尔定理，对称性，收敛条件', stars: 4 },
  { id: '3.3', chapter: 3, title: '非周期信号傅里叶变换', scope: '傅里叶变换定义式，常见信号的傅里叶变换', stars: 5 },
  { id: '3.4', chapter: 3, title: '傅里叶变换性质', scope: '尺度、时移、频移、微分、积分、卷积、帕塞瓦尔', stars: 5 },
  { id: '3.5', chapter: 3, title: '周期信号傅里叶变换', scope: '周期信号的傅里叶变换求解方法', stars: 3 },
  { id: '3.6', chapter: 3, title: '调制与解调', scope: '调制与解调原理，频谱搬移、滤波、解调', stars: 4 },
  { id: '3.7', chapter: 3, title: 'LTI 系统的频域分析', scope: 'H(jω)、正弦稳态响应', stars: 5 },
  { id: '3.8', chapter: 3, title: '无失真传输', scope: '无失真传输的时域、频域特性', stars: 4 },
  { id: '3.9', chapter: 3, title: '理想低通滤波器', scope: '理想低通滤波器时域和频域表达式、图像', stars: 4 },
  { id: '3.10', chapter: 3, title: '佩利-维纳准则与实际滤波器', scope: '了解即可', stars: 1 },
  { id: '4.1', chapter: 4, title: '拉普拉斯变换', scope: '定义式、收敛域、常用函数的拉氏变换', stars: 5 },
  { id: '4.2', chapter: 4, title: '拉普拉斯变换的性质', scope: '时移、s 域平移、微分积分、初终值、卷积', stars: 5 },
  { id: '4.3', chapter: 4, title: '拉普拉斯逆变换', scope: '部分分式法求逆变换，考虑 ROC', stars: 5 },
  { id: '4.4', chapter: 4, title: '拉氏变换与傅里叶变换的关系', scope: '频响存在性', stars: 4 },
  { id: '4.5', chapter: 4, title: '线性系统的复频域分析', scope: '拉氏变换求零输入响应、零状态响应', stars: 5 },
  { id: '4.6', chapter: 4, title: '系统函数与系统特性', scope: 'H(s)、h(t)、零极点及影响系统特性、框图、正弦稳态响应', stars: 5 },
  { id: '4.7', chapter: 4, title: '系统的稳定性', scope: '系统稳定性概念、极点及 ROC 判断稳定性、劳斯判据', stars: 4 },
  { id: '5.1', chapter: 5, title: '引言（抽样）', scope: '了解即可', stars: 1 },
  { id: '5.2', chapter: 5, title: '时域抽样定理', scope: '冲激序列抽样，奈奎斯特频率', stars: 3 },
  { id: '5.3', chapter: 5, title: '频率混叠与抽样频率选择', scope: '不作为重点', stars: 1 },
  { id: '5.4', chapter: 5, title: '内插重建信号', scope: '不作为重点', stars: 1 },
  { id: '5.5', chapter: 5, title: '频域抽样定理', scope: '不作为重点', stars: 1 },
  { id: '5.6', chapter: 5, title: '信号的截断与时窗', scope: '不作为重点', stars: 1 },
  { id: '5.7', chapter: 5, title: '连续时间信号的量化', scope: '不作为重点', stars: 1 },
  { id: '6.1', chapter: 6, title: '离散时间信号——序列', scope: '常用序列、基本运算、性质和画图', stars: 5 },
  { id: '6.2', chapter: 6, title: '卷积和', scope: '定义、图解、性质、对位相乘', stars: 5 },
  { id: '6.3', chapter: 6, title: '线性移不变系统', scope: '线性、移不变、因果、稳定等含义及判断', stars: 5 },
  { id: '6.4', chapter: 6, title: '离散时间系统的时域分析', scope: '差分方程建立与求解、零输入响应和零状态响应、完全响应', stars: 5 },
  { id: '6.5', chapter: 6, title: '离散相关', scope: '不作为重点', stars: 1 },
  { id: '7.1', chapter: 7, title: 'z 变换的定义及收敛域', scope: 'z 变换定义式、ROC 对应的序列性质、典型序列 z 变换', stars: 5 },
  { id: '7.2', chapter: 7, title: 'z 反变换', scope: '部分分式、长除法', stars: 5 },
  { id: '7.3', chapter: 7, title: 'z 变换的基本性质和定理', scope: '移位、初终值、卷积等，适用条件需要注意', stars: 5 },
  { id: '7.4', chapter: 7, title: 'z 变换与拉氏变换、傅里叶变换的关系', scope: '三者联系的约束条件需要了解', stars: 2 },
  { id: '7.5', chapter: 7, title: '序列的傅里叶变换（DTFT）', scope: 'DTFT 定义、常见信号的 DTFT、性质', stars: 4 },
  { id: '7.6', chapter: 7, title: '利用 z 变换解差分方程', scope: '单边 z 变换求零输入响应，双边 z 变换求全响应', stars: 5 },
  { id: '7.7', chapter: 7, title: '离散系统的系统函数和频率响应', scope: 'H(z)、极零图、因果稳定、H(e^jω)', stars: 5 },
  { id: '7.8', chapter: 7, title: '离散系统信号流图', scope: '信号流图和框图的画法', stars: 2 },
  { id: '8.1', chapter: 8, title: '系统的状态变量描述', scope: '无需了解', stars: 1 },
  { id: '8.2', chapter: 8, title: '状态方程建立', scope: '无需了解', stars: 1 },
  { id: '8.3', chapter: 8, title: '状态方程的求解', scope: '无需了解', stars: 1 },
  { id: '8.4', chapter: 8, title: '系统的可控制性和可观测性', scope: '无需了解', stars: 1 },
];

export const CHAPTERS: Record<number, string> = {
  1: '第一章 信号与系统概述',
  2: '第二章 连续时间系统时域分析',
  3: '第三章 傅里叶变换',
  4: '第四章 拉普拉斯变换',
  5: '第五章 抽样与量化',
  6: '第六章 离散时域分析',
  7: '第七章 z 变换',
  8: '第八章 状态变量分析',
};
