import type { Paper } from '../types';

export const papers: Paper[] = [
  { id: 'zt2026', year: 2026, examType: '初试', kind: '真题', title: '2026 初试真题（808）', totalScore: 150 },
  ...[2025, 2024, 2023].map(year => ({ id: `zt${year}`, year, examType: '复试' as const, kind: '真题' as const, title: `${year} 复试真题（回忆版）`, recall: true })),
  { id: 'zt2018', year: 2018, examType: '复试', kind: '真题', title: '2018 复试真题' },
  ...[2017, 2016].map(year => ({ id: `zt${year}`, year, examType: '复试' as const, kind: '真题' as const, title: `${year} 复试真题`, totalScore: 150 })),
  { id: 'tk-review', year: 0, examType: '—', kind: '题库', title: '信号与系统复习题' },
  { id: 'tk-total', year: 0, examType: '—', kind: '题库', title: '信号与系统总复习' },
  { id: 'hw1', year: 0, examType: '—', kind: '习题', title: '王明泉第 1 章课后习题' },
  { id: 'hw2', year: 0, examType: '—', kind: '习题', title: '王明泉第 2 章课后习题' },
  { id: 'hw3', year: 0, examType: '—', kind: '习题', title: '王明泉第 3 章课后习题' },
  { id: 'hw4', year: 0, examType: '—', kind: '习题', title: '王明泉第 4 章课后习题' },
  { id: 'hw5', year: 0, examType: '—', kind: '习题', title: '王明泉第 5 章课后习题' },
  { id: 'hw6', year: 0, examType: '—', kind: '习题', title: '王明泉第 6 章课后习题' },
  { id: 'hw7', year: 0, examType: '—', kind: '习题', title: '王明泉第 7 章课后习题' },
  { id: 'tk-key', year: 0, examType: '—', kind: '题库', title: '重点题必看（手写整理）' },
  { id: 'tk-exam-01', year: 0, examType: '—', kind: '题库', title: '中北课程题库 01（考试试题及答案）', totalScore: 100 },
  { id: 'tk-exam-02', year: 0, examType: '—', kind: '题库', title: '中北课程题库 02（考试试题及答案）', totalScore: 100 },
  { id: 'tk-exam-03', year: 0, examType: '—', kind: '题库', title: '中北课程题库 03（考试试题及答案）', totalScore: 100 },
  { id: 'tk-exam-04', year: 0, examType: '—', kind: '题库', title: '中北课程题库 04（考试试题及答案）', totalScore: 100 },
  { id: 'tk-exam-05', year: 0, examType: '—', kind: '题库', title: '中北课程题库 05（考试试题及答案）', totalScore: 100 },
  { id: 'tk-exam-06', year: 0, examType: '—', kind: '题库', title: '中北课程题库 06（考试试题及答案）', totalScore: 100 },
  { id: 'tk-exam-07', year: 0, examType: '—', kind: '题库', title: '中北题库第 7 套（原卷未编号）', totalScore: 100 },
  { id: 'tk-exam-08', year: 0, examType: '—', kind: '题库', title: '中北课程题库 08（考试试题及答案）', totalScore: 100 },
  { id: 'tk-exam-09', year: 0, examType: '—', kind: '题库', title: '中北题库第 9 套（原卷未编号）', totalScore: 100 },
  { id: 'tk-exam-10', year: 0, examType: '—', kind: '题库', title: '中北课程题库 10（考试试题及答案）', totalScore: 100 },
  { id: 'tk-exam-11', year: 0, examType: '—', kind: '题库', title: '中北课程题库 11（考试试题及答案）', totalScore: 100 },
  { id: 'tk-exam-12', year: 0, examType: '—', kind: '题库', title: '中北课程题库 12（考试试题及答案）', totalScore: 100 },
  { id: 'tk-exam-13', year: 0, examType: '—', kind: '题库', title: '中北课程题库 13（考试试题及答案）', totalScore: 100 },
  { id: 'tk-exam-14', year: 0, examType: '—', kind: '题库', title: '中北课程题库 14（考试试题及答案）', totalScore: 100 },
  { id: 'tk-exam-15', year: 0, examType: '—', kind: '题库', title: '中北课程题库 15（考试试题及答案）', totalScore: 100 },
  { id: 'ext-xaut2024', year: 2024, examType: '初试', kind: '真题', school: '西安理工大学', title: '西安理工 2024 · 810（精选）', selection: '13 个单元，基础变换、卷积与系统分析。按题面比较接近中北常规计算量。', referenceUrl: 'https://yjsy.xaut.edu.cn/2.1.pdf' },
  { id: 'ext-sau2024', year: 2024, examType: '初试', kind: '真题', school: '沈阳航空航天大学', title: '沈航 2024 · 808（精选）', selection: '12 个单元，波形、s/z 域与响应，综合题拆成可单独练习的小问；状态方程未入选。', referenceUrl: 'https://dzx.sau.edu.cn/info/1109/1576.htm' },
  { id: 'ext-sxu2024', year: 2024, examType: '初试', kind: '真题', school: '山西大学', title: '山西大学 2024 · 841（精选）', selection: '8 个单元，以变换、响应和抽样补充训练；计算量稍大的题按用时匹配。', referenceUrl: 'https://yjszsw.sxu.edu.cn/docs/2023-09/0bd43c4677944ee190e0c090125c0fd0.pdf' },
];
